### ISSUE TITLE
Customiser box issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/Parallax-One#100]
@rodica-andronache @cristian-ungureanu Avem o mica problema cu box-urile. De exeplu la sectiunea de About us daca incerc sa adaug mai mult text nu functioneaza. Am incercat sa adaug 4 paragrafe si nu imi este afisat decat primul.

**Comment by mileamadalin** [comment]
@rodica-andronache @cristian-ungureanu Tot aici mi se pare un Must Have compatibilitatea cu html. Este dificil pentru client sa nu poata folosi paragrafe de exemplu.

O alta chestie interesanta pe care o putem face aici, ar fi ca la toate box-urile cu scris, sa avem un chenar patrat de text ca cel din sectiunea About us. Pentru ca este frustrant si dificil de customizat un text lung.

**Comment by cristian-ungureanu** [comment]
@ineagu , aici afara de our story, mai e vreo sectiune care trebuie sa suporte html? Am adaugat suport pentru urmatoarele taguri p,br,em,strong,ul,li  ... mai e nevoie de ceva?

**Comment by ineagu** [comment]
e ok.
