### ISSUE TITLE
blog font weight is too small

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#101]
@claudiuvertistudio fontul de pe blog e f greu de citit, as pune weight 500 + as face mai gri din culoare, ce zici ?

**Comment by claudiuvertistudio** [comment]
pe homepage? sau / si pe pagina de blog / posturi?

**Comment by ineagu** [comment]
blog/posturi in special

**Comment by claudiuvertistudio** [comment]
am pus font weight la pe tot textul din site, acum pare sa se vada mult mai bine si pe posturi. Uita-te si tu sa vezi daca e ok asa sau vrei sa las font-weight doar pe blog/post

**Comment by ineagu** [comment]
doar pe blog/post, am comentat in alt issue :D parca se vedea mult mai fain prima pagina inainte.

asa cum zisesem as face si textul mai gri, cum se vedea inainte

**Comment by claudiuvertistudio** [comment]
@ineagu poti sa te uiti sa vezi daca e ok acum?

**Comment by ineagu** [comment]
pare ok .
