### ISSUE TITLE
font on comments is too small

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#102]
@claudiuvertistudio se vede f dubios cand incerci sa lasi un comentariu, e prea mic fontul.

**Comment by ineagu** [comment]
@claudiuvertistudio when I type the content in the textarea the font is still too small : http://www.awesomescreenshot.com/image/378520/53d565686a72e40ca9388f7645cdf470

**Comment by claudiuvertistudio** [comment]
@ineagu am facut, poti sa te uiti sa vezi daca e ok acum?

**Comment by ineagu** [comment]
pareo k
