### ISSUE TITLE
font on blog postmeta

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#108]
@claudiuvertistudio font on blog postmeta is a bit more bolded in design : http://www.awesomescreenshot.com/image/378505/8fc112795c93597bb2e05c03b3727d00 .
@DragosBubu 
Also on that area I was thinking that we can either lower the transparency or remove it  and increase the featured image size a bit like this : http://www.awesomescreenshot.com/image/378513/edcade54cc8dacf5c0033d876baaa80a ( I just removed transparency and darken the color a bit )

**Comment by claudiuvertistudio** [comment]
@ineagu https://drive.google.com/a/vertistudio.com/file/d/0B-5bubkEZeL-SHNYVDNjQjNpdjQ/edit?usp=drivesdk

nu e o idee tocmai buna sa renuntam la banda transparenta... daca vrei, mutam meta post sub poza

**Comment by ineagu** [comment]
e ok, o sa mai vedem cu bara aia cum ramane, nu ziceam sa renuntam, poate sa scadem transparenta/scoatem
