### ISSUE TITLE
implement schema markup

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#112]
@rodica-andronache @cristian-ungureanu @claudiuvertistudio nu am vazut sa avem schema.org markup, sunt o multime de locuri unde putem adauga, de ex pt blog : 

<article id="post-4724" class="post-4724 post type-post status-publish format-standard has-post-thumbnail hentry category-business category-general sbc-even" itemscope="" itemtype="http://schema.org/BlogPosting">

```
        <header class="entry-header">
    <span class="posted-on">Posted on <a href="http://demo2.woothemes.com/storefront/2014/09/01/birds-in-flight-and-the-power-of-a-remote-working-team/" rel="bookmark"><time class="entry-date published" datetime="2014-09-01T10:38:15+00:00">September 1, 2014</time><time class="updated" datetime="2014-10-01T10:58:54+00:00" itemprop="datePublished">October 1, 2014</time></a></span><span class="byline"> by <span class="vcard author"><span class="fn" itemprop="author"><a class="url fn n" rel="author" href="http://demo2.woothemes.com/storefront/author/woostore/">Sentient User</a></span></span></span><h1 class="entry-title" itemprop="name headline"><a href="http://demo2.woothemes.com/storefront/2014/09/01/birds-in-flight-and-the-power-of-a-remote-working-team/" rel="bookmark">Birds In Flight And The Power Of A Remote Working Team</a></h1> 
```

Se poate folosi asta : https://developers.google.com/structured-data/testing-tool/ ( testati de ex : http://demo2.woothemes.com/storefront/blog/ )

**Comment by cristian-ungureanu** [comment]
@ineagu , cred ca e gata taskul asta, m-am straduit sa-l fac cat am putut de bine, am reusit sa validez toate paginile, inclusiv pagina de single ... pana la urma am declarat-o ca o pagina web normala si i-am bagat autor, data publicarii si ce am mai crezut eu ca mai trebuie ... astept sa vad zeriful cum iese dar in principiu eu zic ca e ok

**Comment by ineagu** [comment]
ok
