### ISSUE TITLE
frontpage is wrongly implemented

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#115]
frontpage is wrongly implemented, if we try to set for example about page as frontpage, this won't work, look in front-page.php for zerif like logic.

**Comment by ineagu** [comment]
@rodica-andronache

**Comment by cristian-ungureanu** [comment]
@ineagu , ce e pe zerif nu e de ajuns, acolo zice asa ... daca e setat static page, ia template-ul de page, altfel afisaza frontpage ...  ce faci daca pagina pe care o vrea ca frontpage are un anumit template? Ar trebui rescrise toate templateurile folosind get_template_part ... practic cam tot codul e la fel, doar ca se apeleaza get_template_part cu alt parametru.

**Comment by cristian-ungureanu** [comment]
am vazut asta la cei de pe underscores.me , acum cand faci o tema noua, asa o structureaza, cu template parts

**Comment by ineagu** [comment]
nu inteleg aici..

**Comment by cristian-ungureanu** [comment]
la zerif, este asa if ( get_option( 'show_on_front' ) == 'page' ) { /*Afisaza continutul paginii cu template-ul de page*/ } else {/* arata frontpage*/} .... ideea e ca poate utilizatorul vrea sa afiseza o pagina care are setat template-ul de full width, totusi lui o sa ii afiseze cu sidebar

**Comment by ineagu** [comment]
mie nu mi se pare asa, daca ma uit la zerif lite :
http://dev2.themeisle.com/zerif-lite/wp-admin/customize.php si setez shop
ca si frontpage, imi apare fara sidebar de ex .

2015-07-06 16:21 GMT+02:00 cristian-ungureanu <notifications@github.com>:

**Comment by cristian-ungureanu** [comment]
Am facut o pagina cu template-ul full width....asta normal ar trebui sa fie fara sidebar .... totusi daca o setez pe frontpage arata sidebarul

**Comment by cristian-ungureanu** [comment]
Cum e la noi template-ul de contact page, acolo e chemat si formularul ala default...daca am pune pagina de contact ca frontpage probabil nu se mai afisaza decat continutul, fara formular

**Comment by cristian-ungureanu** [comment]
@ineagu , cum fac aici pana la urma? Ai vazut despre ce vorbesc?
