### ISSUE TITLE
missing home.php

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#116]
We are missing home.php that basically should include the blog template, do not just duplicate the code like zerif lite case, just include a template in both places. 

@rodica-andronache @cristian-ungureanu

**Comment by ineagu** [comment]
@cristian-ungureanu what I said actually was that in https://github.com/cristian-ungureanu/Parallax-One/blob/production/template-blog.php we should have get_home_template() as well :).

index.php as lasa cum era inainte, in principiu are putin alt rol, nu prea are legatura cu blogul .

**Comment by cristian-ungureanu** [comment]
@ineagu , nu inteleg ... daca las index.php ca inainte si in template-blog.php chem get_home_template(), ce pun in home.php?

**Comment by ineagu** [comment]
in home lasi ce e acum.
