### ISSUE TITLE
Plugin territory: Contact form

### ISSUE THREAD

**Issue by emiluzelac** [Codeinwp/Parallax-One#119]
[../content-contact.php](https://github.com/Codeinwp/Parallax-One/blob/development/content-contact.php)

---

Regardless of Customizer integration, contact forms are plugin territory, sorry.

**Comment by ineagu** [comment]
@emiluzelac  this is a tricky thing, I would need to think a lot about it, however wp core at the moment does a bad job integrating plugins with themes in a way that makes sense for newbies, so my focus is on extreme simplicity for the end users and there are 2 solutions that I see : 

1) Have the contact forms in the theme
2) Have it in a plugin, but automatically install and activate the plugin when the theme is activate, while notifying users about it

As you see both solutions doesn't require any extra single step from the user which is what I am looking to achieve with it, if you have a better solution I would be really happy to listen :)

**Comment by emiluzelac** [comment]
If this is a .org theme, neither one would be accepted. 1) is falls under plugin-territory and 2) must not be done when theme is activated. 

You're more than welcome to use TGM if recommending plugins, but that's as far as this can go I am afraid.

**Comment by ineagu** [comment]
@emiluzelac forget .org thing, I build things for users not for .org admins, so let me know what do you think from this perspective :)

**Comment by emiluzelac** [comment]
To me personally I would not, there is lots of plugins out there that can do this nicely and majority of users prefer plugin over theme integration.

And as always, it's up to you to decide.

**Comment by ineagu** [comment]
there are indeed, however atm I consider that the experience for the user is too segmented, what I considering is to automatically install+configure a plugin, so the user will get the site 'ready' .

**Comment by ineagu** [comment]
@cristian-ungureanu ok let's simply remove built-in contact form and leave just the cf7 shortcode option ( we should might use the logic to create a cotact page plugin ) .

**Comment by cristian-ungureanu** [comment]
@ineagu, should i suggest CF7 with tgm?

**Comment by ineagu** [comment]
initially I would not to avoid suggesting too many plugins, just mention in
documentation + a direct link from customizer

**Comment by justintadlock** [comment]
> forget .org thing, I build things for users not for .org admins, so let me know what do you think from this perspective :)

I just wanted to comment on this as I was catching up on what Emil has done so far.  Both he and I have helped shape the .org guidelines.  These guidelines are always created with the user perspective in mind first.  Our review process is centered on that (as reviewers and fellow developers), but probably a bit stiffer than those guidelines.

Our review is just that though -- a review.  You can always choose to go another direction if review points we bring up don't fit into what you want to do.

With all that said, what I'd personally do is make sure that all forms look good.  Sound design principles are sound design principles.  Your theme should look good with any form from any plugin.  However, I'd pick a single contact form to integrate with and make sure it looks extra good.
