### ISSUE TITLE
Post thumbnails: Prefixing

### ISSUE THREAD

**Issue by emiluzelac** [Codeinwp/Parallax-One#120]
[../functions.php](https://github.com/Codeinwp/Parallax-One/blob/development/functions.php#L86-95)

---

`add_image_size` should have unique and consistent prefixes.

```
    /* Set the image size by cropping the image */
    add_image_size( 'post-thumbnail-big', 730, 340, true );
    add_image_size( 'post-thumbnail-tablet', 730, 340, true );
    add_image_size( 'post-thumbnail-mobile', 730, 340, true );
    // Latest news Section (homepage)
    add_image_size( 'post-thumbnail-latest-news', 150, 150, true );     
    add_image_size( 'parallax_one_team', 268, 273, true );
    add_image_size( 'parallax_one_services',60,62,true );
    add_image_size( 'parallax_one_customers',75,75,true );
```

Please see: http://themereview.co/prefix-all-the-things/

**Comment by ineagu** [comment]
more than this, why we repeat the first 3 add_image_size with the same sizes ?

add_image_size( 'post-thumbnail-big', 730, 340, true );
    add_image_size( 'post-thumbnail-tablet', 730, 340, true );
    add_image_size( 'post-thumbnail-mobile', 730, 340, true );
