### ISSUE TITLE
Scripts: Theme bundle

### ISSUE THREAD

**Issue by emiluzelac** [Codeinwp/Parallax-One#122]
[../functions.php](https://github.com/Codeinwp/Parallax-One/blob/development/functions.php#L191)

---

All scripts must be theme-bundled, unless there is an option to choose between bundled and hosted elsewhere.

**Comment by ineagu** [comment]
@emiluzelac I don't agree on this one, if we add an option, can we still have external by default? Is stupid I think to update the theme each time a script like this change, this is more a contact form issue that we will debate in that issue

**Comment by emiluzelac** [comment]
@ineagu This applies if you're submitting to .org only. JS doesn't update that often anyways and we always have extra stuff to add. Unfortunately bundled must be default.

**Comment by ineagu** [comment]
@emiluzelac we don't plan to do this (submit to wporg ) due to various reasons, at least in the first months, if we will decide to do it later on, we might just fork this .

**Comment by emiluzelac** [comment]
It's still better practices, but since you're not submitting to .org, there
is no requirement elsewhere.

**Comment by ineagu** [comment]
@cristian-ungureanu if we remove contact form thing it means that we can also get rid of captcha, 1 problem less to worry about :)

**Comment by cristian-ungureanu** [comment]
@ineagu , i removed contact form and captcha, can i close this issue?

**Comment by ineagu** [comment]
yes
