### ISSUE TITLE
Plugin territory: Favicons

### ISSUE THREAD

**Issue by emiluzelac** [Codeinwp/Parallax-One#125]
[../header.php](https://github.com/Codeinwp/Parallax-One/blob/development/header.php#L17)

---

When Favicons are not wrapped in options and turned off by default, they become plugin-territory.
Also worth mentioning is that 4.3 will include site icons anyways, you might want to consider removing completely: http://wptavern.com/wordpress-4-3-adds-new-site-icons-feature-and-a-text-editor-to-press-this

**Comment by ineagu** [comment]
@rodica-andronache @cristian-ungureanu I would remove this completely
