### ISSUE TITLE
WooCommerce: Design

### ISSUE THREAD

**Issue by emiluzelac** [Codeinwp/Parallax-One#127]
When theme is activated and WooCommerce in place and front-page pointing to default WooCommerce Shop page the text is barely visible:

---

![screen shot 2015-07-05 at 11 53 57 pm](https://cloud.githubusercontent.com/assets/1784526/8515906/7e97754e-2371-11e5-9982-07a7ea4b3882.png)

**Comment by ineagu** [comment]
@claudiuvertistudio this is more a general front-page issues, not only woocommerce doesn't work

**Comment by cristian-ungureanu** [comment]
@ineagu ,to fix this I would remove the background image control and add just a header image control. Claudiu said that we should let both controls but I don't think that background image helps the user, it looks really bad with a background image on other pages than front-page.

**Comment by ineagu** [comment]
We can leave the background image control, but empty by default. Users can simply add a pattern there
