### ISSUE TITLE
Customizer: Front page displays

### ISSUE THREAD

**Issue by emiluzelac** [Codeinwp/Parallax-One#129]
Front page displays has a radio button, but no pages to choose once clicked.

---

![screen shot 2015-07-06 at 12 04 22 am](https://cloud.githubusercontent.com/assets/1784526/8515974/b2da22b0-2372-11e5-99bd-ec4ee86e4038.png)

**Comment by ineagu** [comment]
@emiluzelac we have another open issue about this.
