### ISSUE TITLE
Customizer: Header logo

### ISSUE THREAD

**Issue by emiluzelac** [Codeinwp/Parallax-One#131]
Header logo was set by default, but the image is blank.

---

![screen shot 2015-07-06 at 12 12 47 am](https://cloud.githubusercontent.com/assets/1784526/8516033/d90edccc-2373-11e5-9568-9698e84f5e1a.png)

**Comment by cristian-ungureanu** [comment]
The image is there but it's white (same as customizer background color) with transparent background.

**Comment by emiluzelac** [comment]
What purpose does this serve?

**Comment by cristian-ungureanu** [comment]
http://prntscr.com/7prb81
