### ISSUE TITLE
Woocommerce related products issue

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#141]
@claudiuvertistudio here is how the related products looks like : http://www.awesomescreenshot.com/image/383765/57030d76201f8d55301e3695f79b3a84 .

**Comment by claudiuvertistudio** [comment]
@ineagu Done

**Comment by ineagu** [comment]
@claudiuvertistudio @cristian-ungureanu this still doesn't look very good no ? http://demo.themeisle.com/parallax-one/product/isobound/

**Comment by ineagu** [comment]
category listing looks bad as well : http://demo.themeisle.com/parallax-one/product-category/parallax-one/

**Comment by cristian-ungureanu** [comment]
@ineagu , la products e un script js pentru repozitionare, in cazul in care un produs are pret si altul nu, sa faca resize si butonul sa fie la aceeasi inaltime... ideea e ca e foarte costisitor ca si timp scriptul asta, se apeleaza mereu la resize sau la load si are in el o chestie de genul setTimeout(function(){  }, 200);...pe local merge ok dar pus pe server crapa cand timpul de incarcare al pozelor e mai mare...d-aia nu arata ok butoanele alea decat dupa resize ...plus ca apare foarte ciudat cand se face resize ... eu unul as merge pe varianta asta http://suprb.com/apps/gridalicious/ + o bordura in jurul produsului ... scriptul asta s-a folosit si pe prima pagina la services in cazul in care sunt boxurile de diferite marimi ... sau mai simplu, un min-height. Ce parere ai?

**Comment by ineagu** [comment]
putem discuta asta cu claudiu, + intreaba pe rodica ea cum are de gand la faca la shopisle / sau cum e facut la storefront :D

**Comment by cristian-ungureanu** [comment]
storefront n-are nimic, nici macar un min-height ... eu asa l-as lasa ... cred ca sunt pluginuri care fac asta

**Comment by ineagu** [comment]
Cum asa ? Fara js ala ?

**Comment by cristian-ungureanu** [comment]
Fara Js, fara min-height ... cum e si storefront. Cel mult as pune gridalicious sa arate bine daca sunt elemente de diferite unaltimi. JS-ul ala, pe langa faptul ca e apelat la resize si are in el timeout, elementele nu sunt adresate direct prin id, mai mananca timp si parsarea.

**Comment by ineagu** [comment]
Ok, hai sa incercam asa
