### ISSUE TITLE
Customizer: PRO version

### ISSUE THREAD

**Issue by emiluzelac** [Codeinwp/Parallax-One#142]
Adding in PRO version items are still in gray area, something team didn't discuss yet, but since this was allowed in Theme Options, I don't see why we would do differently in Customizer.

Now, one issue here is that when you mouse-over it feels like `Check out the PRO version for full control over homepage sections order !` is a link which doesn't go anywhere.

---

![screen shot 2015-07-06 at 12 45 12 pm](https://cloud.githubusercontent.com/assets/1784526/8529064/31809bde-23dd-11e5-8626-1def44a2ead7.png)

**Comment by ineagu** [comment]
@emiluzelac those will go out, the theme will be released as free only, not upsell whatsoever.
