### ISSUE TITLE
about text inconsistency

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#151]
@claudiuvertistudio the about text looks very bad compared with the original html, here is how it looks for us : http://www.awesomescreenshot.com/image/384247/894255dc5b4644a5da92d53ae97ac0c7 and how it should look : http://www.awesomescreenshot.com/image/384250/fc8cdb525484bd86a96177c7a3daae95, pay attention at fonts/spaces etc etc, it should be perfectly like there.

**Comment by claudiuvertistudio** [comment]
@ineagu Done
