### ISSUE TITLE
Better compatibility with WPPR

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#152]
@claudiuvertistudio we would need some custom css for WPPR to make sure it looks good and in the same way as the existing fonts/text/spacing :+1: 

http://dev2.themeisle.com/parallax-one/hello-world/

Same for widgets, comments .

We should also automatically display the rating on the blog listing for reviews ( if the plugin is activated ) like : http://www.engadget.com/reviews/cellphones/ or https://wordpress.org/themes/reviewgine-affiliate/

**Comment by claudiuvertistudio** [comment]
@ineagu 

![v1](https://cloud.githubusercontent.com/assets/3263086/15361426/207626ba-1d1a-11e6-9956-1e761440eedd.jpg)
![v2](https://cloud.githubusercontent.com/assets/3263086/15361427/21f35f8a-1d1a-11e6-8b48-008b67bd68a4.jpg)
![v3](https://cloud.githubusercontent.com/assets/3263086/15361431/29d43dd2-1d1a-11e6-88b3-50419fca9777.jpg)

**Comment by ineagu** [comment]
1 sau 2 as zice eu, andrei ce parere are ?

On Wed, May 18, 2016 at 4:01 PM, Claudiu Buruiana <notifications@github.com>
wrote:

> @ineagu <https://github.com/ineagu>
>
> [image: v1]
> <https://cloud.githubusercontent.com/assets/3263086/15361426/207626ba-1d1a-11e6-9956-1e761440eedd.jpg>
> [image: v2]
> <https://cloud.githubusercontent.com/assets/3263086/15361427/21f35f8a-1d1a-11e6-8b48-008b67bd68a4.jpg>
> [image: v3]
> <https://cloud.githubusercontent.com/assets/3263086/15361431/29d43dd2-1d1a-11e6-88b3-50419fca9777.jpg>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/152#issuecomment-220035206>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by abaicus** [comment]
Cred ca 2 mi se pare cea mai eleganta. Si 1 e ok dar poate ca ar merge mai degraba cu culoarea din 2. :+1:
