### ISSUE TITLE
Remove textarea customizer control

### ISSUE THREAD

**Issue by justintadlock** [Codeinwp/Parallax-One#156]
Core WP has a built-in textarea customizer control (since 4.0, I believe).  You can remove the custom control and use core's.  Use `'type' => 'textarea'` when adding the control.

**Comment by ineagu** [comment]
@justintadlock I think we use our own to accept some basic html there, is this something that we can do with the core one ?

**Comment by justintadlock** [comment]
We're just talking about the control here.  What's allowed is in the setting and how you sanitize/validate that data on input and output.

**Comment by ineagu** [comment]
thanks for clarification.
