### ISSUE TITLE
Use get_template_directory_uri()

### ISSUE THREAD

**Issue by justintadlock** [Codeinwp/Parallax-One#158]
There's 20 instances in 8 different files where the theme is using `get_stylesheet_directory_uri()`.  You can get all of these with a search for `get_stylesheet_directory_uri` in your code editor or here on GitHub.

Only use that function if referencing a child theme.  If referencing something in the parent (Parallax One) theme, use `get_template_directory_uri()` instead.

**Comment by ineagu** [comment]
@justintadlock if we use get_template_directory_uri, we won't be able later on to modify those through a child-theme right ? We plan to have 5-10 child themes probably doign different things, so being extremely child themes friendly is important

**Comment by justintadlock** [comment]
It'll break custom child themes that don't have those.  If you want to overwrite it with a child theme, you have two options:

* Create a filter hook to allow it to be overwritten.
* Check for the existence of the file in the child theme and fallback to the parent theme if it doesn't exist.

**Comment by ineagu** [comment]
@cristian-ungureanu @rodica-andronache @selu91 can you investigate more on this ? especially filter/hook think ?

**Comment by cristian-ungureanu** [comment]
@justintadlock , get_template_directory_uri() already use a filter named 'template_directory_uri' ... can we use it in our child themes ?

**Comment by justintadlock** [comment]
> get_template_directory_uri() already use a filter named 'template_directory_uri' ... can we use it in our child themes ?

That definitely doesn't it in with this use case.  That's a filter hook for overwriting the entire parent theme directory URI and should only be accessed with extreme caution.

It's not all that hard to do a `if ( file_exists( get_stylesheet_directory() . 'file.ext' ) ) { echo get_stylesheet_directory_uri() . '/file.ext' ); }` check.
