### ISSUE TITLE
Blog Template

### ISSUE THREAD

**Issue by justintadlock** [Codeinwp/Parallax-One#160]
This page template should be removed in favor of the core-supported `home.php`.  `home.php` is the proper template for the blog page.  A custom page template doesn't support core-defined functionality for the blog page.

**Comment by ineagu** [comment]
@justintadlock yes, but we need it due to the latest news behaviour.

**Comment by ineagu** [comment]
@cristian-ungureanu did you tested this, blog got broken on demo : http://demo.themeisle.com/parallax-one/blog/ .

**Comment by cristian-ungureanu** [comment]
i think now it is ok ... sorry, that was my fault
