### ISSUE TITLE
Front page implemented incorrectly

### ISSUE THREAD

**Issue by justintadlock** [Codeinwp/Parallax-One#161]
When I've selected to show "latest posts" via "Settings > Reading", a custom front page is shown instead.  What the theme should do in this case is to show the latest posts (i.e., the blog).  The custom front page stuff should only be shown when a page is set as the front page.

Related: #160. I recommend reading: http://www.chipbennett.net/2013/09/14/home-page-and-front-page-and-templates-oh-my/

**Comment by ineagu** [comment]
@justintadlock for the moment we don't plan to change this ( we might fork the theme and change if we will decide to submit to the repo ).

The current settings->reading implementation is stupid and my efforts to change that were ignored by a long list of people that I have tried to get attention :D, so as much as I would love to follow the wp core settings, in this case I don't want to follow a thing that I believe is wrong ( we also discussed this several times ).

Responsive which is/was one of the most popular wp themes does it, zerif which will probably be one of the most popular themes of 2015 does it, so for me this looks a better solution.

I will be really happy to hear another solution that will get the one-page frontpage automatically activated for the user when the theme is activated or with a minimum effort and attention, like 1sec thing for a new user to wp .

**Comment by justintadlock** [comment]
I'm just reporting that the theme is handling the setting incorrectly as part of the review..  You're more than welcome to not follow the correct, core-support implementation.  That's up to you and your team.

The rest of the discussion is outside the scope of the review.  I'd be happy to discuss it elsewhere.

**Comment by ineagu** [comment]
sure thing, thanks for reporting it :)
