### ISSUE TITLE
Never use query_posts()

### ISSUE THREAD

**Issue by justintadlock** [Codeinwp/Parallax-One#162]
99.9% of the time, themes shouldn't use `query_posts()`.  

One of those times is in `template-blog.php`, which I recommended removing in #160.  This is probably the only legitimate use case, so it's OK to use it there.

However, in `parallax_one_latest_news_section.php`, that should be a `new WP_Query()` instead of `query_posts()`.  The usage of `query_posts()` there breaks all kinds of conditionals, and thus, breaks plugins that rely on those conditionals.

**Comment by ineagu** [comment]
@cristian-ungureanu feel free to investigate this.
