### ISSUE TITLE
Customizer: Pro/Support links bleed through

### ISSUE THREAD

**Issue by justintadlock** [Codeinwp/Parallax-One#164]
Take a look at the attached screenshot.  The pro and support links/buttons bleed through when accessing a panel.

![customizer-design](https://cloud.githubusercontent.com/assets/1816309/8559966/aed527f2-24d8-11e5-9a8f-cfa96e044aab.png)

**Comment by ineagu** [comment]
@justintadlock any special setting/version to replicate ? I can't see it.

**Comment by justintadlock** [comment]
Running WP trunk, latest revision.
