### ISSUE TITLE
Style: Galleries broken

### ISSUE THREAD

**Issue by justintadlock** [Codeinwp/Parallax-One#165]
Take a look at the screenshot.  Galleries are not lined up in columns.  The screenshot is for a 3-column gallery.  I've tested 1-10 columns with the same results.

![gallery](https://cloud.githubusercontent.com/assets/1816309/8560043/80ccf35c-24d9-11e5-8b52-034201982d5f.png)

**Comment by claudiuvertistudio** [comment]
@ineagu Done
