### ISSUE TITLE
Save and Update Issue (Pages and Posts)

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/Parallax-One#184]
@rodica-andronache @claudiuvertistudio @cristian-ungureanu @ineagu 

When I try to save or update a page like Contact for example or, a Post from Posts section I see this error:

http://awesomescreenshot.com/0ff52hg0ab

**Comment by cristian-ungureanu** [comment]
@mileamadalin , asta nu e de la tema, e de la vreun plugin...am schimbat tema si am incercat sa adaug o pagina, la fel face

**Comment by mileamadalin** [comment]
@cristian-ungureanu am rezolvat problema. De la un plugin este si l-am dezactivat pana la urma. Nu stiam ce era cu el.
