### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/Parallax-One#2]

**Comment by ineagu** [comment]
@rodica-andronache pt asta ar mai trebui cred sa mai asteptam sa schimbam logo/imagine din header / imagine de background daca nu e gpl, sa ne hotaram ce o sa avem si ce nu ( gen client logos alea pe lite )

**Comment by rodica-andronache** [comment]
stiu :) am facut doar issue, ca sa nu uitam
