### ISSUE TITLE
Github button

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#204]
@rodica-andronache what do you think about adding a github link near the documentation /forum ? so people can contribute/raise issues easier ?

**Comment by rodica-andronache** [comment]
@ineagu I think it's a very good idea. We should do that for zerif lite too, right?

**Comment by ineagu** [comment]
we can on lite, however there are already too many links there so we need to find a way to limit them. for example updagrade to pro it can be moved like you see on Make theme, can you investigate ?

**Comment by rodica-andronache** [comment]
@ineagu ok, we'll add it on parallax, and I will investigate for zerif
