### ISSUE TITLE
oEmbed not responsive

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/Parallax-One#212]
I have noticed that the oEmbed (https://codex.wordpress.org/Embeds#oEmbed) does not work quite right for videos, specifically YouTube. If you go to http://demo.themeisle.com/parallax-one/video-post/ and look at a landscape view on a tablet that is 1024 x 768 (or use Firefox Responsive Design View or resize any browser) then the YouTube video does not resize properly and instead goes into the sidebar.

@ineagu @rodica-andronache

**Comment by rodica-andronache** [comment]
@cristian-ungureanu aici cred ca ar trebui modificat 
.parallax-one-video-container iframe, .parallax-one-video-container object, .parallax-one-video-container embed {
    max-width: 100%;
    max-height: 100%;
}

Pt ca altfel nu mai ia in considerare dimensiunile gen:
[embed width="123" height="456"]http://www.youtube.com/watch?v=dQw4w9WgXcQ[/embed]
