### ISSUE TITLE
Theme is not accesibility ready

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#214]
@claudiuvertistudio @cristian-ungureanu as vrea sa investigam ce zice aici : https://make.wordpress.org/themes/handbook/review/accessibility/ si sa ne asiguram ca tema poate sa fie utilizata si pt site-uri care sunt cititite de oameni cu dizabilitati .

**Comment by ineagu** [comment]
asta e mai prioritar aici cristi.

**Comment by ineagu** [comment]
sa te uiti si pe Schema.org microdata cand pui tag-uri pentru asta.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu 
acum cand se apasa pe butoanele din meniu, se pune border: http://prntscr.com/8ece2z banuiesc ca nu e ok, pt ca nu era asa inainte. Stiu ca e pt accessibility probabil, dar nu cred ca e ok.
cred ca se pune la toate butoanele http://prntscr.com/8ecett

**Comment by cristian-ungureanu** [comment]
https://make.wordpress.org/themes/handbook/review/accessibility/required/#keyboard-navigation

Theme authors MUST provide visual keyboard focus highlighting in navigation menus and for form fields, submit buttons and text links. Navigation by keyboard should also be intuitive and effective.

**Comment by rodica-andronache** [comment]
ok. @ineagu tu ce crezi? lasam asa?

**Comment by ineagu** [comment]
pot sa vad un demo undeva ? Daca schimbarile modifica tema prea mult, am
putea avea o setare in customizer ->settings cu un checbox : accesibility
ready + explicatii

On Wed, Sep 9, 2015 at 2:03 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> ok. @ineagu <https://github.com/ineagu> tu ce crezi? lasam asa?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/214#issuecomment-138888462>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
@ineagu @cristian-ungureanu poate, cum a facut tipul ala la zerif lite? A pus in customizee checkbox pt accesibility cum ai zis si tu? Mie una mi se pare vizibila rau modificarea de la butoane

**Comment by cristian-ungureanu** [comment]
Pentru demo http://test-2408.qsandbox.com/ - Access Code 000

Daca ziceti ca am voie sa pun un checkbox in customizer pentru accessibility ready, o sa fac asa...n-am stiut ca e voie. Chiar ma gandeam cum rezolv partea cu contrastul.

**Comment by ineagu** [comment]
nu stiu sigur daca e voie, dar cred ca in principiu o sa fie de apreciat
chiar si atat.

O putem pune in zona aia de required actions, gen if you want your website
to be accesibilty ready, do this ( which will change contrast + x )

2015-09-10 10:24 GMT+03:00 cristian-ungureanu <notifications@github.com>:

> Pentru demo http://test-2408.qsandbox.com/ - Access Code 000
>
> Daca ziceti ca am voie sa pun un checkbox in customizer pentru
> accessibility ready, o sa fac asa...n-am stiut ca e voie. Chiar ma gandeam
> cum rezolv partea cu contrastul.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/214#issuecomment-139137293>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by cristian-ungureanu** [comment]
Ideea e ca astia zic asa: 
https://make.wordpress.org/themes/handbook/review/accessibility/required/#contrasts
The default settings will be the only color scheme checked. If a theme offers multiple color schemes, only the default scheme is required to pass these guidelines. Iar la noi, default va fi cea care e acum.

Eu as face asa: as lasa partea de focus cum e acum....poate doar sa o fac putin mai eleganta, gen cum e la zerif ..... partea asta de contrast as lasa-o asa cum e, poate avem noroc si trece ... daca nu, macar aflam cam ce vor cei de la wp legat de contrast, punem o intrebare legat de asta, daca accepta sau nu checkbox cu enable accessibility

**Comment by ineagu** [comment]
pt contrast da, am putea modifica noi putin, dar pt faza cu meniu, tot
trebuie checkbox

2015-09-10 12:02 GMT+03:00 cristian-ungureanu <notifications@github.com>:

> Ideea e ca astia zic asa:
>
> https://make.wordpress.org/themes/handbook/review/accessibility/required/#contrasts
> The default settings will be the only color scheme checked. If a theme
> offers multiple color schemes, only the default scheme is required to pass
> these guidelines. Iar la noi, default va fi cea care e acum.
>
> Eu as face asa: as lasa partea de focus cum e acum....poate doar sa o fac
> putin mai eleganta, gen cum e la zerif ..... partea asta de contrast as
> lasa-o asa cum e, poate avem noroc si trece ... daca nu, macar aflam cam ce
> vor cei de la wp legat de contrast, punem o intrebare legat de asta, daca
> accepta sau nu checkbox cu enable accessibility
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/214#issuecomment-139175844>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
