### ISSUE TITLE
optimize gmap

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#231]
@cristian-ungureanu ar trebui sa incarcam google maps-ul ca la zerif pro, adica nu la incarcarea paginii

se poate ?

**Comment by cristian-ungureanu** [comment]
@ineagu , tin minte ca am incercat asta cu marius dar nu a mers...mi-a zis marius atunci ca ar trebui modificat intergeo sa aiba o optiune de lazy load, sa se incarce dupa ce au fost incarcate toate sectiunile

**Comment by ineagu** [comment]
@cristian-ungureanu ok, si ce ne opreste sa adaugam un filtru in plugin :D ? ca e tot al nostru
