### ISSUE TITLE
Allowing customizer.php to be changed in a child theme

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/Parallax-One#232]
Great job on the theme – I love it and I’m now trying to modify it via a child theme.

To do so, I need to modify the menus that appear in the Theme Customizer, specifically in the Ribbon section. The idea is to have something similar to the About section (title + text), but still use the ribbon format and the button.

Delving into you .php files, my understanding is that doing so via a child theme would be impossible because you use require get_template_directory() . ‘/inc/customizer.php’; to access customizer.php instead of require get_stylesheet_directory() . ‘/inc/customizer.php’;. It appears that you could also have used the locate_template() function to allow the child theme to override this.

Any ideas on how I can get this done?

Aici banuiesc ca poti folosi acceasi functie, care verifica daca fisierul exista in child

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , nu pot folosi functia aia decat pe fisiere ce nu sunt .php ... In orice caz nu, e nevoie de asa ceva ... dupa ce a creat child-theme-ul, sa faca un fisier functions.php acolo si sa puna functia asta 

function parallax_one_childtheme_customize_register( $wp_customize ) {
	$wp_customize->add_setting( 'parallax_image_child' );
 
	$wp_customize->add_control(
		new WP_Customize_Image_Control(	$wp_customize,'parallax_image_child',
			array(
				'label' => __('New parallax control from child theme','parallax-one'),
				'section' => 'parallax_one_ribbon_section',
				'priority'   => 15
			)
		)
	);
}
add_action( 'customize_register', 'parallax_one_childtheme_customize_register' );

Asta adauga un nou control de imagine in customizer in sectiunea de ribbon ... si ma rog, poate el/ea sa-si defineasca orice control vrea, sau sa le scoata pe ale noastre etc etc

**Comment by rodica-andronache** [comment]
@cristian-ungureanu am inteles asta. Poti investiga si tu daca vrei faza asta cu load_template sugerata de o clienta http://themeisle.com/forums/topic/change-file-included-with-require/. Eu am incercat la zerif si mi s-a parut ok, dar ionut zicea ca nu stie sigur si sa intreb pe slack. Daca imi raspund ceva, iti zic :)
