### ISSUE TITLE
Add Hooks

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/Parallax-One#233]
Like on flat 
https://github.com/codeinwp/flat#available-hooks
https://github.com/woothemes/storefront/blob/master/inc/structure/hooks.php

**Comment by rodica-andronache** [comment]
https://github.com/Codeinwp/zerif-pro/issues/336

**Comment by rodica-andronache** [comment]
@cristian-ungureanu aici ai lasat in hooks.php:

niste do_action( 'tha_header_top' ); banuiesc ca nu trebuie folosite sau ma insel?

**Comment by cristian-ungureanu** [comment]
L-am facut sa fie compatibil cu tha hooks, ma rog, atat cat s-a putut. M-am luat dupa flat ( https://github.com/Codeinwp/flat/blob/master/dist/inc/hooks.php )

**Comment by cristian-ungureanu** [comment]
Se vrea a fi un oarecare standard ( https://github.com/zamoose/themehookalliance )

**Comment by rodica-andronache** [comment]
@cristian-ungureanu ok, nu stiam
