### ISSUE TITLE
add welcome page

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#243]
@rodica-andronache @cristian-ungureanu 

In order to upload this on w.org we should : 
- add welcome sections similar to zerif lite ( ideally the code can be easily added )
- remove shortpixel
- make sure the new theme-checker is ok, add all tags that make sense 

In a separate branch/file : 
- change how reading setting works
- remove the code that stop w.org updates 
- version should be 1.0 (we should use to for the ti version )

Next week we should upload the new version .

**Comment by rodica-andronache** [comment]
@cristian-ungureanu pana la urma nu o sa mai facem versiunea pt wp.org cel putin deocamdata.
