### ISSUE TITLE
Option to hide a section

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/Parallax-One#251]
Since we're keeping the hide button option to a future Pro version, the logical way in the Lite version could be to hide the empty section. If the section is empty, then don't display it. How about that? :)

@rodica-andronache @ineagu

**Comment by cristian-ungureanu** [comment]
@ineagu , asta era si stiu ca ai zis sa o scoatem ... ce fac?

**Comment by rodica-andronache** [comment]
@cristian-ungureanu aici a ramas cum a zis Hardeep. adica daca nu are nimic in sectiunea aia se se ascunda. Nu cu buton de hide

**Comment by cristian-ungureanu** [comment]
Am inteles, ok :)
