### ISSUE TITLE
captcha on comments

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#262]
I see here that somebody is using a captcha plugin for comments : http://owenthe.ninja/about-me-and-what-i-do/ , can we see what plugin he used and how to fix that visual issue ?

**Comment by cristian-ungureanu** [comment]
Pluginul folosit este cel de aici https://wordpress.org/plugins/wp-recaptcha/ ... genereaza multe erori in tema, nu prea e indicat sa-l foloseasca. Am adaugat style si pentru el.
