### ISSUE TITLE
Re-sizing browser hides Our services and our team - critical issue

### ISSUE THREAD

**Issue by qualityking** [Codeinwp/Parallax-One#264]
Hi there, 
I have just upgraded my theme and found it messed up on the smaller devices, doesn't show full site data and hides additional boxes of our services and our team.
please treat this a critical bug

**Comment by rodica-andronache** [comment]
@qualityking thank you very much for reporting this. We will take this in consideration as an important bug.

@cristian-ungureanu can you please have a look here? Thanks
