### ISSUE TITLE
portfolio and pricing in plus version

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#266]
@rodica-andronache @cristian-ungureanu   Due to the better control that we have with the welcome section + tgma, we can in the plus version to add pricing section + portfolio through already existing plugins, for pricing we have one already and we can look for an effective one for portfolio part .

**Comment by cristian-ungureanu** [comment]
moved to https://github.com/Codeinwp/parallax-one-plus/issues/2
