### ISSUE TITLE
Sorting always replace position 1 with 2

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/Parallax-One#268]
Every type of sorting replace the positions of the first 2 items, example can be seen here when sorting by price: dev2.themeisle.com/parallax-one/shop/?orderby=price

The same problem is on the widgets used in the front-page for all sections, first widget will get second position and vice-versa.

It happens everywhere where sorting is involved.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu daca te uiti pe dev2 http://dev2.themeisle.com/parallax-one/shop/ se afiseaza doar  3 produse pe pagina, desi sunt mai multe. Si daca navighezi intre pagini, se incarca un pic dubios
