### ISSUE TITLE
Allow html to be added in each section

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/Parallax-One#272]

**Comment by happypig** [comment]
Great to see it!!!

**Comment by rodica-andronache** [comment]
@cristian-ungureanu maybe be should add this to the Header section and Ribon too

**Comment by happypig** [comment]
Is html tag li also possible? Many thanks.

BTW, the whole 3 text boxes in Service section are all gone after I insert tag br in one of the box. No box will be displayed no matter how many boxes I added after.

http://themeisle.com/forums/topic/correct-link-for-switching-the-right-language-page-in-headerribbon-button/

**Comment by rodica-andronache** [comment]
@happypig we'll sure consider adding support for li tag.
Regarding the testimonials boxes, as I answered on your thread, for me it's working fine, so please check the  thread for details. Thank you

**Comment by rodica-andronache** [comment]
@cristian-ungureanu maybe be should add this to the Header section and Ribon too

**Comment by Brosper** [comment]
When this feature will this be added?

**Comment by rodica-andronache** [comment]
@cristian-ungureanu for colors you shouldn't be using parallax_one_sanitize_input http://prntscr.com/bhkkuf

Also, checkboxs like paralax_one_enable_move should have another sanitize_callback, no parallax_one_sanitize_input
