### ISSUE TITLE
specific characters are bold in translation

### ISSUE THREAD

**Issue by alexandrastann** [Codeinwp/Parallax-One#292]
http://www.archit.lt/ the website is Lithuanian and the specific characters are in bold while the site is viewed on Mozilla or IE. Works ok in Chrome.

**Comment by rodica-andronache** [comment]
http://www.icra.com.pl/
http://prntscr.com/9s0rca
not working in IE

**Comment by claudiuvertistudio** [comment]
I added a new option for character sets in Advanced options.
