### ISSUE TITLE
Display error in "Services Section" 

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/Parallax-One#293]
@rodica-andronache @cristian-ungureanu @claudiuvertistudio 

" When using special character (prime symbol ‘ or backslash ) in the description of a service (into service box), a warning is displayed and all service boxes disappears. I can use other special character without issue.
The same issue exist in the conact section

Steps to reproduce:
1. Customize the parallax theme
2. Open the service section
3. Add or edit a service
4. Type prime symbol ‘ or backslash \ in the description : the error message is displayed "

**Comment by rodica-andronache** [comment]
@cristian-ungureanu ar mai fi cateva campuri in care se intampla problema asta:
team widget : subtitle and title
testimonials widget: title, subitle

Si cum am mai zis, nu ar fi ok ca in customizer.php inainte de foreach ($input_decoded as $boxk => $box )
sa verifici vectorul ala nu sa fie gol?
