### ISSUE TITLE
Plugins Breaking

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/Parallax-One#294]
@rodica-andronache @cristian-ungureanu 

We have this message from a customer:
"
We are using two plugins, one is called Machforms and the other is Shortcodes Ultimate. The Machform plugin will only appear some of the time and when it’s in the body of pages, it pushes widgets down, disrupting their alignment. The second plugin is called Shortcodes Ultimate, we are using it to create an accordion style drop down for in-page content. The accordion won’t open.
"

We must fix these issues in the upcoming updates :)

**Comment by ineagu** [comment]
@mileamadalin we need more descriptive titles and separation : 

- Breaking accordion style dropdown in SU is not a big deal at all, isn't breaking the plugin
- MachForms is a kind of not-popular script builder which probably breaks the html.

@s2abina I would mention to the support team that is very important to create relevant issues, with good title/description and tested before.

1. If a client report an issue try to replicate it
2. If is an issue, search it across our forums/docs/ github ( include closed issues), maybe we decided to ignore it, or created a doc for it

@mileamadalin sorry for using this as an example.
