### ISSUE TITLE
Remove github button from customize

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/Parallax-One#298]
@ineagu should be remove it? like on zerif?

**Comment by ineagu** [comment]
yes

On Wed, Oct 21, 2015 at 10:25 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> should be remove it? like on zerif?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/298>.
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
