### ISSUE TITLE
Console warning

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/Parallax-One#304]
The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

in plugin.home.js

**Comment by claudiuvertistudio** [comment]
I can't do anything for this warning message and it comes from the parallax.js plugin. It's just a warning message and doesn't stop anything working.
