### ISSUE TITLE
Pro version won't install on 4.3.1

### ISSUE THREAD

**Issue by extremesurfer** [Codeinwp/Parallax-One#309]
During installation on a vanilla WP 4.3.1 the install exits with unable to find styles.css

**Comment by rodica-andronache** [comment]
@extremesurfer thank you for reporting this issue, but could you please give us more details? I just tested and everything worked ok

**Comment by rodica-andronache** [comment]
@extremesurfer I think I figured out what the issue is. You are trying to install it as a theme, but Parallax One Plus is a plugin, and should be installed from Plugins -> Add new.
Please let me know if that is the case.

**Comment by extremesurfer** [comment]
Thanks - you nailed it. Plugin and not a theme!
