### ISSUE TITLE
Line break in textbox adds unnecessary "n"

### ISSUE THREAD

**Issue by kashmirix** [Codeinwp/Parallax-One#311]
Adding line break (CR+LF) to textbox (for example, in the Contacts section) results in no line break but a character "n" added.

Ideally, line break in the box should be rendered as such (i.e., as `<br/>`).

Workaround: use `<br/>` if you need line breaks in a box. It does not look neat (and requires some html knowledge from users) but works.

**Comment by rodica-andronache** [comment]
@kashmirix thanks for the suggestion. We will definitely consider this.
