### ISSUE TITLE
Child theme not working when PO Plus is installed

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/Parallax-One#315]
I have made for the Parallax Theme a child Theme. there I have the folder "sections" with the file "parallax_one_latest_news_section.php". when I hange the html or Php of this file normaly it change the section in the frontend.
Now I have activated the Parallax One plus plugin an the changes I made doesn't work. Now I have to change the HTML or PHP in the plugin folder parallax-one-plus > public > templates. But when you make an update for the plugin all my changes are deleted. Why doesn't work the changes in my child theme folder?

I don't know if there is a solution for this, but I think we should investigate

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , se poate face childtheme si la Parallax One Plus, trebuie doar o anumita structura https://drive.google.com/file/d/0BxF3mFOrA6MvVG4tOFNkZ1o4V1k/view?usp=sharing ... poate ne ajuta @mileamadalin cu o documentatie.

**Comment by mileamadalin** [comment]
Desigur. Ma ocup. O documentatie pentru cum sa creezi un child teme pentru Parallax One Plus? Adica structura si toate cele?

**Comment by rodica-andronache** [comment]
@mileamadalin daca aia e structura de child theme de la care se poate pleca, cred ca o poti adauga in documentatie, sa poata fi downloadata, si sa scrii ca de la ea se pleaca. Cum e la zerif, cu child theme-ul sample

**Comment by mileamadalin** [comment]
ok, atunci asa fac. merci

**Comment by rodica-andronache** [comment]
@cristian-ungureanu aici ai vorbit cu madalin? Daca e totul gata, ar trebui facuta documentatie, cum se face exact. Ca intreaba oamenii

**Comment by cristian-ungureanu** [comment]
Ah, scuze....stiu ca era de mult discutia...am presupus ca e gata. @mileamadalin ?

**Comment by rodica-andronache** [comment]
@cristian-ungureanu din ce am vorbit eu cu madalin, parca ramasese sa vorbesti cu el sa-i explici cum se face cu filtre si hook-uri ca sa faca docul

**Comment by cristian-ungureanu** [comment]
ok, atunci ne ocupam maine

**Comment by rodica-andronache** [comment]
@cristian-ungureanu documentatia asta este gata nu? daca da, inchide issue-ul te rog :)

**Comment by cristian-ungureanu** [comment]
Asta se va rezolva cand se va face merge la https://github.com/Codeinwp/parallax-one-plus/pull/60 ... scheletul pentru child-theme este atasat iar documentatia este aici http://docs.themeisle.com/article/264-how-to-create-a-child-theme-if-you-use-parallax-one-plus
( @mileamadalin , te rog sa mai arunci un ochi peste ea, nu stiu daca ai facut update dupa ce am reparat problema aceea ca nu puteau fi inlocuite decat sectiunile din lite)
[parallax-child.zip](https://github.com/Codeinwp/Parallax-One/files/238758/parallax-child.zip)

**Comment by rodica-andronache** [comment]
@mileamadalin te rog saptamana asta sa te ocupi de chestia asta. Sa vezi daca e ok, si sa actualizezi in documentatie sau unde trebuie. E destul de urgent :)

**Comment by mileamadalin** [comment]
@cristian-ungureanu @rodica-andronache  aici stiu ca modificasem documentatia dupa ce ai modificat. Verific din nou, testez si revin in curand

**Comment by rodica-andronache** [comment]
@mileamadalin cum merge aici? :D

**Comment by mileamadalin** [comment]
@rodica-andronache Din pacate nu am vesti prea bune. Testasem si nu mergea. Vorbisem cu @cristian-ungureanu sa se mai uite o data acolo ca nu functionza. De indata ce se rezolva te anunt.

**Comment by mileamadalin** [comment]
@rodica-andronache @cristian-ungureanu @selul Mai avem un client care raporteaza problema si spune asa:

Child theme creation error

I'm trying to create a child theme for Parallax One Plus per the instructions in this article:

http://docs.themeisle.com/article/264-how-to-create-a-child-theme-if-you-use-parallax-one-plus

1 st problem - the at the end of the functions.php code causes a syntax error. I removed that

Now, I receive the following error:

Fatal error: Call to undefined function boolval() in /data/webs/art4healing.org/art4healing.org/htdocs_dev/wp-content/themes/ACFH-parallax-one-child/functions.php on line 26

I have double checked the styles.css and functions.php files and have copied/pasted your text from the article twice.

Credeti ca este posibil sa rezolvam saptamana asta? Sau daca nu sa imi spuneti cand estimati ca o putem rezolva?

**Comment by mileamadalin** [comment]
@rodica-andronache @cristian-ungureanu @selul We have a suggestion from a customer:

Hi. I got it fixed by adding this function before the call to boolval as a workaround:

if (!function_exists('boolval')) {
function boolval($val) {
return (bool) $val;
}
}

can you please check it and see if that fix this issue?

**Comment by cristian-ungureanu** [comment]
@mileamadalin , @rodica-andronache , this should work now.

**Comment by mileamadalin** [comment]
@rodica-andronache @cristian-ungureanu I test it right now

**Comment by mileamadalin** [comment]
@cristian-ungureanu trebuie sa modificam documentatia acum pentru ca functioneaza in alt mod, vorbim maine la birou despre asta

**Comment by mileamadalin** [comment]
@rodica-andronache am clarificat cu Cristi aici si acum totul functioneaza. Acum modific deja documentatia. Voi inchide aici.

**Comment by rodica-andronache** [comment]
@mileamadalin cand e gata documentatia, sa o pui si aici te rog, ca sa o punem in pagina de about din tema

**Comment by mileamadalin** [comment]
@rodica-andronache documentatia este gata: http://docs.themeisle.com/article/264-how-to-create-a-child-theme-if-you-use-parallax-one-plus
