### ISSUE TITLE
Section background opacity

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/Parallax-One#322]
Opacity control for section images. @rodica-andronache

**Comment by rodica-andronache** [comment]
@HardeepAsrani can you please give more details? :D

**Comment by HardeepAsrani** [comment]
@rodica-andronache Alpha control so people could change the background's opacity. :)

**Comment by cristian-ungureanu** [comment]
@rodica-andronache aici sau in plus?

**Comment by rodica-andronache** [comment]
@ineagu what do you think? I would add it in Parallax One

**Comment by ineagu** [comment]
Have no idea

**Comment by rodica-andronache** [comment]
@mariusghitulescu then what do you think? :D

**Comment by mariusghitulescu** [comment]
For free, I would suggest we add it for the first section only (the one with parallax background), so people know this feature exists and how it works.

Then, for every other section I would make it unavailable and suggest that it's only available for PRO. If we don't have it available anywhere in free version, I think most people would not know what this feature is.
