### ISSUE TITLE
Change of domain name results in losing all Parallex settings

### ISSUE THREAD

**Issue by timinho** [Codeinwp/Parallax-One#332]
I had to change the domain name for a WP site using Parallex-One but all links to images seem to be stored with the full url in the option table. I copied the json from 'theme_mods_Parallax-One', did a find&replace on the domain and updated the record. The result was that I lost all settings and it showed the default Parallax content. Luckily I had a backup but what should be the procedure to change the domain?

**Comment by ineagu** [comment]
@Rodicaelena I think we can offer an export/import function. There are some existing plugins as well, we can first check if they work

**Comment by timinho** [comment]
@ineagu any news on this topic?

**Comment by cristian-ungureanu** [comment]
@timinho , please try this plugin: https://ro.wordpress.org/plugins/customizer-export-import/ . On your old website go to Customize -> Export and click the Export button. This will generate a file named Parallax-One-export.dat. On your new website install this plugin again, go to Customize -> Export -> Choose file and select Parallax-One-export.dat ( or just drag and drop the file on the button). Also check "Download and import image files?". Please let me know if this solve your problem.
