### ISSUE TITLE
Adding social icons to team section

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/Parallax-One#339]
It will be good to add some icons in the team section. @rodica-andronache

**Comment by cristian-ungureanu** [comment]
@ineagu , what do you think?

**Comment by ineagu** [comment]
not sure about what is this about, if you have question for me is better to provide context, screenshots etc, I don't really know how the section/settings looks like :)

**Comment by cristian-ungureanu** [comment]
@ineagu , it's about social icons in team section ... when we developed the theme we chose to remove them
![po_icons_1024](https://cloud.githubusercontent.com/assets/9929553/12882890/3e7968e0-ce5d-11e5-925b-78d8e18bb3ca.jpg)

**Comment by Brosper** [comment]
As a user I would like to have them :)

**Comment by ineagu** [comment]
@cristian-ungureanu ok, we can have them .

**Comment by cristian-ungureanu** [comment]
@Brosper , thank you for your feedback and for using Parallax One. This feature will be available in the next update.
