### ISSUE TITLE
Full width no title template page

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#345]

**Comment by rodica-andronache** [comment]
@ineagu what do you mean here?

**Comment by ineagu** [comment]
if you look here :
http://demo.themeisle.com/parallax-one-staging/drag-and-drop-builder-compatible/,
it would have been much better without the title and the space at the top

On Fri, Jan 22, 2016 at 1:59 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> what do you mean here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/345#issuecomment-173914071>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by NathanTheGr8** [comment]
I was having this issue to actually with the zerif theme. The code seems the similar in this theme. I think you would just need to remove lines 10-14 in content-page.php.

<header class="entry-header">
		<?php the_title( '<h1 class="entry-title single-title" itemprop="headline">', '</h1>' ); ?>
		<div class="colored-line-left"></div>
		<div class="clearfix"></div>
</header>

removing those lines with remove the header problem you speak of. Now the problem is I don't know all the places this file is being used and if it will break some other function. I just over wrote the file in my child theme.

**Comment by rodica-andronache** [comment]
Hi @NathanTheGr8 ,

Thank you for contacting us. Yes, we'll add this option in Zerif too. We already added an issue for this.

Thank you,
Rodica

**Comment by cristian-ungureanu** [comment]
@ineagu , how about this:  to avoid creating a new template file, i'll put a class that have margin top 0. This class will appear if the page don't have a title and it's set as frontpage.

**Comment by ineagu** [comment]
is not about frontpage, is about internal pages with drag&drop builders. I
guess it can work, if there is no title to start from very top ( do a test
with siteorigin plugin )

On Wed, Feb 3, 2016 at 3:15 PM, cristian-ungureanu <notifications@github.com
> wrote:

> @ineagu <https://github.com/ineagu> , how about this: to avoid creating a
> new template file, i'll put a class that have margin top 0. This class will
> appear if the page don't have a title and it's set as frontpage.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/345#issuecomment-179259204>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
@cristian-ungureanu shouldn't this work on internal pages, like ionut said? right how i see the class .no-top-margin only on homepage

**Comment by cristian-ungureanu** [comment]
Oh, I forgot about this...Now it works when the page has no title and it is
setted as frontpage.

@cristian-ungureanu <https://github.com/cristian-ungureanu> shouldn't this
work on internal pages, like ionut said? right how i see the class
.no-top-margin only on homepage

—
Reply to this email directly or view it on GitHub
<https://github.com/Codeinwp/Parallax-One/issues/345#issuecomment-185161844>
.

**Comment by ineagu** [comment]
it should work like rodica said, not for frontpages only

On Wed, Feb 17, 2016 at 12:37 PM, cristian-ungureanu <
notifications@github.com> wrote:

> Oh, I forgot about this...Now it works when the page has no title and it is
> setted as frontpage.
>
> @cristian-ungureanu <https://github.com/cristian-ungureanu> shouldn't this
> work on internal pages, like ionut said? right how i see the class
> .no-top-margin only on homepage
>
> —
> Reply to this email directly or view it on GitHub
> <
> https://github.com/Codeinwp/Parallax-One/issues/345#issuecomment-185161844
> >
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/345#issuecomment-185164458>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
