### ISSUE TITLE
Issue with Russian fonts

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/Parallax-One#349]
Services section isn't working properly with Russian fonts. And maybe with other sections too. @rodica-andronache

**Comment by cristian-ungureanu** [comment]
@HardeepAsrani , I tried with some russian text but it looks fine to me. Can you be more specific? Also, Parallax-One have a control in Customizer -> Advanced options -> 'Choose the character sets you want' where you can set the types of characters Cyrillic/ Vietnamese/ Greek, maybe this resolve this issue.

**Comment by HardeepAsrani** [comment]
Got it!
