### ISSUE TITLE
sanitize and escape all user data 

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/Parallax-One#354]
https://secure.helpscout.net/conversation/179630287/79469/?folderId=265052

he entered something like /mail.google.com\/mail\/u\/0ox?compose=15347\/#inbe3122e0fd64 target=\"_blank\"\" in the link field of the contact frontpage section and that caused errors on frontpage and customizer to stop working

**Comment by cristian-ungureanu** [comment]
This was fixed in #373 . That's not an usual input. Now those fields supports mail, tel, callto protocols. Also I have no error when inserting that string in the link field.
