### ISSUE TITLE
Make front page SEO compatible

### ISSUE THREAD

**Issue by Gouravwp** [Codeinwp/Parallax-One#357]
Can we make front page a template. So that it can be selected like a normal WordPress page and user can add meta data for that page.

**Comment by rodica-andronache** [comment]
@ineagu should we consider this? I think so

**Comment by ineagu** [comment]
I find it rather confusing to have a frontpage template page with same
content, creating a doc is the best option

On Thu, Apr 7, 2016 at 5:25 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> should we consider this? I think so
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/357#issuecomment-206930299>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
ok we'll create a doc
