### ISSUE TITLE
database entries in wp_options when a site is relocated are not updated.

### ISSUE THREAD

**Issue by jimmymain** [Codeinwp/Parallax-One#360]
Hi,

This is as much of a question as an issue.
I have been deploying my wordpress / parallax site on a test server, and have been struggling with the paths. I note that get_theme_mod returns data in the database.

When the site is moved, it doesn't seem to correctly update these database values to the new paths.
What is the correct way to trigger this update?

I note that there is an action for this update.

```
add_action( 'shutdown', 'parallax_one_add_id' );
```

When should this be triggered?

**Comment by cristian-ungureanu** [comment]
Hello @jimmymain ,

Sorry for my late answer. Please try this plugin https://wordpress.org/plugins/customizer-export-import/ when moving your website. On your old website go to Customize -> Export/Import -> Export and click the Export button. This will generate a file named Parallax-One-export.dat. On your new website install this plugin again, go to Customize -> Export/Import -> Import -> Choose file and select Parallax-One-export.dat ( or just drag and drop the file on the button). Also check "Download and import image files?". Please let me know if this solve your problem.

Don't worry about that action, it's not related whit this question. That was a solution for fixing some translations issues. It runs when the page output is complete.
