### ISSUE TITLE
[suggestion] Blackquote color

### ISSUE THREAD

**Issue by dzienisz** [Codeinwp/Parallax-One#363]
Can you make blackquote color match "hoover" color of the theme?

![000852](https://cloud.githubusercontent.com/assets/3521624/14404096/03669ad8-fe6f-11e5-84c4-8f4748038477.png)

**Comment by rodica-andronache** [comment]
Hi @Brosper ,

Do you still have this issue? I checked your website and it seams you added some custom css for it.

**Comment by Brosper** [comment]
Yes, I made custom CSS but I made a suggestion for you to build it into ParalaxOne Theme.

It will be gone i next theme update because I made all changes to original theme not child theme.

**Comment by rodica-andronache** [comment]
Hi @Brosper unfortunately we can't change this in the theme now, because it would affect all the current users. If you want your custom css to not be lost after updates, you can use a plugin like https://wordpress.org/plugins/advanced-css-editor/ or create a child theme.
Thanks
