### ISSUE TITLE
Сallto link in Contacts section

### ISSUE THREAD

**Issue by Onore** [Codeinwp/Parallax-One#373]
Hello.
If I tried to add  **callto:**+38000000 to filed link in Contacts section of Home page I get link to root domain like http://site.com. 
Please, fix the ability to create custom links.

**Comment by cristian-ungureanu** [comment]
Hello @Onore ,
Thank you for reporting this issue, we will fix this in our next update.

Best regards,
Cristian

**Comment by Onore** [comment]
Hello Cristian.
Thank you.
The same problem exist for button on the first screen - "Позвонить" http://irpenmasters.com/

New Features requests
1. Header for Contacts
2. Map height setting

Because the Contacts block may looks better. Please, see anchor link like http://irpenmasters.com/#contactinfo

Best regards,
Onore

**Comment by Brosper** [comment]
What's going on with this feature?
