### ISSUE TITLE
Polylang issue

### ISSUE THREAD

**Issue by dzienisz** [Codeinwp/Parallax-One#375]
Website have problem changing it's language when is on "other" language.

Issue on:
v2.1.0.8
PC and Mobile
Polish, English

Website: www.icra.com.pl

**Comment by Brosper** [comment]
only on hompage

**Comment by Brosper** [comment]
I use https adres on my website

**Comment by rodica-andronache** [comment]
@Brosper Can you please give more details here? You can't translate some of the strings?

Thank you,
Rodica

**Comment by Brosper** [comment]
How to reproduce.

1. www.icra.com.pl
2. click on "american" flag

Problem is that site don't enter english site on main site but when you enter

1. www.icra.com.pl/subpage
2. click on "american" flag

you normalny enter english page.

WHY?

**Comment by Brosper** [comment]
I turned off https on my website and now works fine

**Comment by rodica-andronache** [comment]
Hi @Brosper ,

Ok, thanks. If this was the problem, you maybe could contact the Polylang support and see if there is a known issue or solution for this. Did you encountered this issue with other themes, or just with Parallax?

Thank you,
Rodica

**Comment by Brosper** [comment]
I tested it only on parallax. I haven't contact Polylang support yet.

**Comment by Brosper** [comment]
if it can help I have problem with line 
![agnieszka i tomasz icra - tniemy raty wordpress001057](https://cloud.githubusercontent.com/assets/3521624/15824850/7989fcae-2c01-11e6-8807-3f01d49ea3af.png)
It was deleted few months ago and it's still in Polylang

**Comment by Brosper** [comment]
Currently it's working ok.

I'm closing this issue.
