### ISSUE TITLE
Subtitles for sections field type

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/Parallax-One#380]
We need to either limit the input of the text field or change the input type to a textbox.

http://themeisle.com/forums/topic/services-section-edit/

**Comment by rodica-andronache** [comment]
yes, we could change all the subtitle fields into textarea

**Comment by Brosper** [comment]
Thanks :)

**Comment by cristian-ungureanu** [comment]
@ineagu , what do you think about this? I think subtitles are short in most cases. We could do this or we could add text content for sections like testimonials, team or features. I think this is more useful.

**Comment by ineagu** [comment]
agree, I think in most cases they are short, if we can enough place in customizer we can do it. also you can look for some sites using the theme and see how people are using it.

Also I don't understand 2nd part of your comment

**Comment by cristian-ungureanu** [comment]
@ineagu , I was thinking something like this. And add a control in customizer.
![screenshot_1](https://cloud.githubusercontent.com/assets/9929553/16079017/8dced1ca-330a-11e6-9439-2a6c2c957b56.png)

**Comment by ineagu** [comment]
ok, I wouldn't do it now.

On Wed, Jun 15, 2016 at 2:05 PM, cristian-ungureanu <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> , I was thinking something like this.
> And add a control in customizer.
> [image: screenshot_1]
> <https://cloud.githubusercontent.com/assets/9929553/16079017/8dced1ca-330a-11e6-9439-2a6c2c957b56.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/380#issuecomment-226167689>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DG-2ZE0_qbagt9L4SrvsCwc5uCgMks5qL-qagaJpZM4Ifa9H>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
@cristian-ungureanu not sure why , but it doesn't seam to work for the Our services subtitle. Can you please check again?
