### ISSUE TITLE
Defaulting to home link if no link provided

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/Parallax-One#385]
If no link is provided to the contact area section widgets it defaults to the website's homepage.

**Comment by rodica-andronache** [comment]
@UVLabs I don't understand what you mean here. Can you please give more details? Thanks :)

**Comment by UVLabs** [comment]
@rodica-andronache I think what I meant here is in the contact area: http://prntscr.com/c7d8n3 if you do not add a link to the icon then the icons default to the site's homepage.

So for example if you're just adding a phone number but don't add the tel: link then the icon will refresh to the page if clicked.

What I had in mind was that if no link provided in the customizer settings then don't echo out a link tag, but currently it is
