### ISSUE TITLE
Add font awesome support for more icon choices

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/Parallax-One#389]
Feature request from user for new icons such as snapchat etc which are available in font awesome

**Comment by dacopan** [comment]
Is more easy search a icon in fontawesome's web page and paste it in a input text in wordpress customizer that search a icon in a large scroll (ddslick).  I saw your source code and think it is not easy to maintain your way to place icons

**Comment by dacopan** [comment]
I can refactor all this to support any webfont pack to replace ddslick with simple input text or autocomplete and send you a pull request

**Comment by ineagu** [comment]
Hey @UVLabs @dacopan,

Current solution is indeed not perfect, however @UVLabs clients can upload an image or add an url, so we don't necessarely need to add this into the theme.

@dacopan instead of ddslick what do you think about something like : https://select2.github.io/examples.html ?  it has sections and search .

**Comment by dacopan** [comment]
could be a good solution, but for example siteorigen page builder includes extensive packages of icons, why not leave the option for the user to directly type your favorite icon? former. 'Fa fa-paw' or 'io-icon'

To take advantage of already loaded icons?

**Comment by ineagu** [comment]
1. there are those icons loaded by default ?
2. All existing icons exist there as well ? ( since we don't want existing
users to be required to change their current icons)
3. I don't think most of the users know about things like fa-twitter or
etc, if we can have something select2 grouped and also when user type some
text to work well, I think is a good improvement, which don't break
existing setups neither.

If we were to start from scratch probably font-awesome would have been
better.

On Tue, Jun 28, 2016 at 8:10 PM, Darwin Correa <notifications@github.com>
wrote:

> could be a good solution, but for example siteorigen page builder includes
> extensive packages of icons, why not leave the option for the user to
> directly type your favorite icon? former. 'Fa fa-paw' or 'io-icon'
>
> To take advantage of already loaded icons?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/389#issuecomment-229133855>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DKm-eT-LUKSc7GQvUaVN0tTbgOMmks5qQWOMgaJpZM4I-dFY>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by dacopan** [comment]
you're right, I'm thinking as a programmer and not as user. :hankey: 
Then it would be ideal keep select control but also give me the option to write the icon directly to power users (fa-xxx or any class) ...

As the case I mentioned: in your select control no has Snapchat icon (contact section, etc), but yes in icons packs ...
so will be utility for those who want to also write directly.

**Comment by ineagu** [comment]
we have the option to upload an image or add an url, if you select image
and not icon, so I think this is kinda covered as well. I mean indeed it
might not be the best way, but the improvement looks like minimal in my
opinion, the only sensitive improvement it will be select2 to get rid of
that super long dropdown :)

On Tue, Jun 28, 2016 at 8:39 PM, Darwin Correa <notifications@github.com>
wrote:

> you're right, I'm thinking as a programmer and not as user. 💩
> Then it would be ideal keep select control but also give me the option to
> write the icon directly to power users (fa-xxx or any class) ...
>
> As the case I mentioned: in your select control no has Snapchat icon
> (contact section, etc), but yes in icons packs ...
> so will be utility for those who want to also write directly.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/389#issuecomment-229142676>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DBCr636A46mv7i2Bs74FFmRKy2ndks5qQWptgaJpZM4I-dFY>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by dacopan** [comment]
In contact sections, social repeaters, not has this options, and is not a good practice and bad performance put very much images or external resources.

**Comment by dacopan** [comment]
the best solution will be included select2 and a option to edit direct.

**Comment by dacopan** [comment]
or better option include a autocomplete control

**Comment by ineagu** [comment]
ok, I get it, I was looking at services section sorry.

We can handle those separately  :

1. For social icons in the footer
- we should rename the fields to Social Profile ( instead of parallax one )
- let users add just the url
- In case those are used, load some css file with rules like
: .social-navigation a[href*="twitter.com"]::before  { icon }

The big advantage here is that users don't need to choose/care about social
icons at all, we just display them based on url. For other cases there are
other solutions that can work the best .

On Tue, Jun 28, 2016 at 9:03 PM, Darwin Correa <notifications@github.com>
wrote:

> or better option include a autocomplete control
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/389#issuecomment-229149421>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DA4PGMboCrhvGO7lDqwZTbBQ3k49ks5qQW_kgaJpZM4I-dFY>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by cristian-ungureanu** [comment]
@ineagu , how about just adding a checkbox "Use font awesome icons" and notice the user that if they check that, they will have to select their icons again? The solution you proposed it's nice but I think it's for future projects. If we do this we will change user's sites.

**Comment by ineagu** [comment]
for this theme at the moment I don't think it makes sense to have the
checkbox, is good enough. having fontawesome won't solve the infinite
dropdown neither.

On Thu, Jun 30, 2016 at 4:54 PM, cristian-ungureanu <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> , how about just adding a checkbox
> "Use font awesome icons" and notice the user that if they check that, they
> will have to select their icons again? The solution you proposed it's nice
> but I think it's for future projects. If we do this we will change user's
> sites.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/389#issuecomment-229683406>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DDivuOm5tkXZMgtotTSJIZV0ZaGuks5qQ9iogaJpZM4I-dFY>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by cristian-ungureanu** [comment]
maybe we can change ddslick with something like this http://codepen.io/matt-west/full/jKnzG ?

**Comment by ineagu** [comment]
this doesn't work in safari, there are just 2 inputs

On Thu, Jun 30, 2016 at 5:07 PM, cristian-ungureanu <
notifications@github.com> wrote:

> maybe we can change ddslick with something like this
> http://codepen.io/matt-west/full/jKnzG ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/389#issuecomment-229687786>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DN6mnj2XPsP09r63FWtTHADtwXLOks5qQ9uegaJpZM4I-dFY>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by dacopan** [comment]
http://projects.sergiodinislopes.pt/flexdatalist/ :gem:

**Comment by ineagu** [comment]
yep something along those lines ( with a search ) can replace ddslick

On Thu, Jun 30, 2016 at 6:56 PM, Darwin Correa <notifications@github.com>
wrote:

> http://projects.sergiodinislopes.pt/flexdatalist/ 💎
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Codeinwp/Parallax-One/issues/389#issuecomment-229720594>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABw6DBnnNbgES0oox7mjJLZAKr0Yv7Ieks5qQ_UvgaJpZM4I-dFY>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by dacopan** [comment]
yes this is my idea, the possibility to 'power user' can write direct the icon. :+1:

**Comment by UVLabs** [comment]
+1
