### ISSUE TITLE
Theme Check One or more errors were found for Parallax One.

### ISSUE THREAD

**Issue by dacopan** [Codeinwp/Parallax-One#391]
- remove deprectaed tags: blue, black, white, etc
- fix some style.css errors
  - 840: line-height: auto;
  - 1698: text-align: !important;
  - 2447: -ms-filter: grayscale(1);
  - 4687: visibility: none;
  - 6092: content: ""; missing ':'

**Comment by ineagu** [comment]
@rodica-andronache can take a look at those, thanks again :)
