### ISSUE TITLE
Option to choose latest news category

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/Parallax-One#394]
I see in the theme itself there's a filter for setting the latest news category "parallax_latest_news_cat" but in the plus plugin there's no filter. Maybe we should add the option to customizer.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu can't this filter be used with the pro plugin too? In a child theme? Can you please check this? 
If so, I think we close this and maybe create a doc if it doesn't exists

**Comment by rodica-andronache** [comment]
@cristian-ungureanu ?

**Comment by cristian-ungureanu** [comment]
After the recent changes to pro, the latest news section in theme will be the same as the plugin. The plugin will search for the latest news template file in theme and require it, Now the plugin have its own file latest news file.

**Comment by rodica-andronache** [comment]
ok. then @UVLabs this will available in the update for parallax one plus. Hopefully this week or the next one
