### ISSUE TITLE
Button Customizer Colors not taking effect

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/Parallax-One#395]
Button color options in customizer actually has no effect on the button color, hover, text color, text hover.

Seems this has been an issue for a while: http://themeisle.com/forums/topic/blue-call-to-action-button-in-header-section-not-changing/

@rodica-andronache @claudiuvertistudio

**Comment by rodica-andronache** [comment]
@UVLabs this is for parallax one plus, not parallax one :) I moved the issue there
