### ISSUE TITLE
WP DEBUG ON - load.php on line 50

### ISSUE THREAD

**Issue by Basilakis** [Codeinwp/Parallax-One#397]
Notice: Undefined index: slug in /hermes/walnaweb07a/b1495/moo.ecopirate/kazandee/wp-content/themes/Parallax-One/vendor/themeisle/load.php on line 50

That is an issue, when activating plugin and have WP Debug turned on.
Yes, a quick solution is to have it off and suggest to users, but still it needs to be fixed

**Comment by UVLabs** [comment]
This currently happens for multiple of our themes such as shopisle and zerif (those iv tested so far), Iv informed @selul 

@rodica-andronache @claudiuvertistudio @Basilakis

**Comment by selul** [comment]
@rodica-andronache @UVLabs @Basilakis this is fixed in the latest SDK. When a new update will go out for those themes, the error should be fixed also

**Comment by Basilakis** [comment]
Ok, thanks for the update, closing the issue
