### ISSUE TITLE
Google Maps warnings

### ISSUE THREAD

**Issue by dzienisz** [Codeinwp/Parallax-One#399]
![2016-07-21 00_38_23-](https://cloud.githubusercontent.com/assets/3521624/17005651/ac62d09a-4edb-11e6-8eaf-3ee46ba0adc5.png)

**Comment by rodica-andronache** [comment]
Hi @Brosper ,

Thank you got contacting us. The warning appear due to Intergeo maps plugin, not from the theme, and it should be fixed in the next update for the plugin, as you can see here the commit where it was fixed : https://github.com/Codeinwp/intergeo-maps/issues/27
