### ISSUE TITLE
Option to set number of latest news shown

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/Parallax-One#400]
@rodica-andronache @claudiuvertistudio Is it possible to add this feature into the customizer? Have had to users request for it.

**Comment by rodica-andronache** [comment]
@UVLabs the number of posts in Latest news section can be changed from here http://prntscr.com/c7axkm.
Is this enough?

**Comment by UVLabs** [comment]
Yes that should be enough, didn't notice, I'm closing this issue.
