### ISSUE TITLE
jQuery errors v2.1.0.12

### ISSUE THREAD

**Issue by dzienisz** [Codeinwp/Parallax-One#409]
![2016-08-19 13_08_36-ustawienia](https://cloud.githubusercontent.com/assets/3521624/17808072/237fb85c-660e-11e6-81c2-0661d3700839.png)

After updating to the newest version v2.1.0.12 i found a lot of errors

Our website: www.icra.com.pl

**Comment by rodica-andronache** [comment]
Hi Brosper,

Thank you for reporting this. We'll investigate this. First, could you please let me know if you are using any caching plugin? And, if that is the case, could you please clear the cache?
Thank you,
Rodica

**Comment by Brosper** [comment]
![2016-08-19 13_34_26-wtyczki icra - tniemy raty wordpress](https://cloud.githubusercontent.com/assets/3521624/17808673/aec80f42-6611-11e6-94b4-1b9b90748190.png)

Yes, it was made by this 2 plugins. I use them to get higher score on Google Page Speed.

**Comment by rodica-andronache** [comment]
Ok, it means the theme is not compatible with those plugins. We'll try to investigate this and see if there is a solution.

Thank you
