### ISSUE TITLE
Remove Logos section

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#41]

**Comment by cristian-ungureanu** [comment]
@ineagu , there is no logos section, only a text control in customizer 'Check out the PRO version to add logos section !' . Do you want me to remove this too?

**Comment by ineagu** [comment]
yes, I am thinking to remove the whole control, is quite useless, it takes too much space in customizer and people won't really understand what logos section is.

We already propose colors, order, team section in the upsell + portfolio and improved shop design .

Also for the upsells in general, I like how Make theme is doing it : http://i1.wp.com/wptheming.com/wp-content/uploads/2015/05/make-upsell.jpg?resize=664%2C423 . By marking whole section/control as PRO, showing how it looks like but disable the functionality .

**Comment by ineagu** [comment]
@cristian-ungureanu hai ca te-am zapacit de tot aici :D , m-am gandit pana la urma sa nu mai punem tema pe wp.org initial si sa mergem pe site-ul nostru, din cateva motive ( daca esti curios le putem discuta ).

Asa ca as zice sa adaugam inapoi partea de logos si in versiunea free, dar sa fie pusa in controlul de header.

**Comment by ineagu** [comment]
@cristian-ungureanu @rodica-andronache aici de ce nu am pus astea in customizer ? si am pus in widgets ? mi se pare putin peste mana sa le punem asa, omu tre sa iasa din control, sa intre in widgets, sa revina.

**Comment by cristian-ungureanu** [comment]
@ineagu , afara de sectiunea cu textul si butonul acela albastru, toate sectiunile sunt widgets. Le pun in customizer aici?

**Comment by ineagu** [comment]
eu asa as zice, tinand cont ca e un element simplu ( imagine/link )

2015-06-22 10:19 GMT+02:00 cristian-ungureanu <notifications@github.com>:
