### ISSUE TITLE
No sidebar in Default template

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/Parallax-One#414]
No sidebar in default template @rodica-andronache

**Comment by rodica-andronache** [comment]
@UVLabs I don't understand this. Both single page and single post have sidebars. Can you please explain?

**Comment by rhj4** [comment]
Check out http://connexions.world. Click on "Bob's Blog" and open either of the posts and you will see the widgets. However, those widgets do not appear on any of the other pages which all use the "default" template. I looked at the generated HTML and it is not a hidden div that is not being displayed. There is no widget content on these pages.

**Comment by rodica-andronache** [comment]
Hi @rhj4 ,

Thank you for contacting us. I checked your site and you are right, there is no sidebar displayed on the internal pages, but I coudn't replicate this on our side. 
Could you please let me know if you did any kind of change in the theme? Also, are you using a plugin for management of the sidebars/widgets like for example https://wordpress.org/plugins/display-widgets/ or https://wordpress.org/plugins/dynamics-sidebars/ ?

Regards,
Rodica

**Comment by rhj4** [comment]
I just disabled all plugins and the problem is still there.

I also remember changing on .css attribute in section 3.1, but I cannot find that file now to see if I undid the change I made. I will keep searching, but at present, here is what is generated as output:

![2016-09-22_9-42-27](https://cloud.githubusercontent.com/assets/3075794/18757505/0b77d25c-80a9-11e6-9461-4fbaa95d1a82.jpg)

**Comment by rodica-andronache** [comment]
Hi @rhj4 ,

We just release an update for the theme. If you want, you could update it, this way all the changes you could have done in the theme files would be overridden and maybe it would solve your issue, as I couldn't replicate it and it doesn't seem to be related to the theme.

Regards,
Rodica

**Comment by UVLabs** [comment]
@rhj4 also make sure that in customizer->General options->General ensure this option is unchecked: http://prntscr.com/cqopa2

**Comment by rhj4** [comment]
Where do I get the upgraded theme?

Bob

**Comment by UVLabs** [comment]
@rhj4 It should be present in Apperance->Themes in your WordPress dashboard. The latest version is 2.1.0.13

**Comment by rhj4** [comment]
I don’t see a “General Options” tab in the Customizer.
[cid:image001.png@01D22089.D296C3F0]


I also don’t know how to get the upgraded theme.

Please Advize.

Bob

**Comment by rodica-andronache** [comment]
Hi,

Uriahs is talking about Customize -> Appearance -> General options.
If you are having trouble updating the theme (if you don't see any update if you go to Appearance -> Themes -> Parallax One) please contact us here http://themeisle.com/contact/.

Regards,
Rodica
