### ISSUE TITLE
Debbuger Console issue

### ISSUE THREAD

**Issue by Basilakis** [Codeinwp/Parallax-One#417]
http://themeisle.com/wp-content/uploads/gravity_forms/1-a802f9b942a19180d258d8ed48e41d68/2016/10/2016-10-02-13_28_17-final.jpg-@-333-RGB_8.png

Please take a look at the screenshot, reported by a client.
Thanks a lot

**Comment by rodica-andronache** [comment]
@Basilakis I don't see this errors on our demo. Did you also check or this is only what the client reported?

**Comment by HardeepAsrani** [comment]
@Basilakis Our themes don't make a call to dashicons so seems like an issue with their site.

**Comment by Brosper** [comment]
What about warnings and legacy methods?

**Comment by HardeepAsrani** [comment]
Is it your site? And some errors are not in English so can't really read those. :)
