### ISSUE TITLE
Add animations

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/Parallax-One#418]
Add animations to the front-page elements like in zerif. 

An option in Customizer ( by default off )

Maybe use [Scrollreveal](https://scrollrevealjs.org/)

@claudiuvertistudio @rodica-andronache 

What do you think? Any suggestions for another animation framework? 👍

**Comment by rodica-andronache** [comment]
we'll add this in lite too?

**Comment by abaicus** [comment]
Yes. Directly into the lite version. 👍

**Comment by rodica-andronache** [comment]
ok :) I don't know other framework. Maybe @claudiuvertistudio knows
