### ISSUE TITLE
General option control

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#42]
We can add few more settings like : 

Disable comments on pages
etc

**Comment by cristian-ungureanu** [comment]
@ineagu , in page.php am linia urmatoare: if ( comments_open() || get_comments_number() ) : care verifica daca commenturile sunt activate/dezactivate din Settings->Discussion ... ce propui, sa renunt la controlul din customizer sau la cel din Settings->Discussion? 
In afara de asta, te-ai mai gandit la vreun control anume?

**Comment by ineagu** [comment]
pai din setarile din wp se pot dezactiva comentariile doar pe pagini si nu
si pe posturi ?

2015-06-16 15:54 GMT+02:00 cristian-ungureanu <notifications@github.com>:

**Comment by cristian-ungureanu** [comment]
Am investigat mai amanuntit ... checkboxul 'Allow people to post comments on new articles' din Settings->Discussion controleaza doar valoarea default a paginilor si a posturilor, atunci cand sunt create sa afiseze sau nu sectiunea de comentarii ... daca in schimb eu vreau ca la un anume post sau la o anumita pagina sa nu fie valoarea default, ma pot duce pe postul/pagina respectiva > screen options > bifez Discussion iar apoi imi arata jos o sectiune de unde pot edita daca vreau alta valoare decat cea default ... deci practic, setarea aia din Settings->Discussion controleaza ambele, pages si posts... pot face control separat in customizer pentru pages care sa fie prioritar, daca e setat, sa ascunda comentariile de pe toate paginile, indiferent de ce alte setari mai sunt facute.

**Comment by ineagu** [comment]
ok, exact asta ziceam :). sa adaugam posibilitatea ca oamenii sa poata
dezactiva comentariile doar la pagini, nu si la posturi .

2015-06-16 16:21 GMT+02:00 cristian-ungureanu <notifications@github.com>:
