### ISSUE TITLE
#home anchor missing

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/Parallax-One#422]
@rodica-andronache theme doesn't have #home anchor anymore, only #parallax_header

**Comment by rodica-andronache** [comment]
@UVLabs i'm not sure about this. we really need it? somebody suggested this?

**Comment by UVLabs** [comment]
+1 @rodica-andronache yes we actually had this for a doc http://docs.themeisle.com/article/59-how-to-link-menu-to-sections-in-parallax-one-and-llorix-one

**Comment by rodica-andronache** [comment]
@UVLabs we have #masthead for both themes, that point to the main header. They can use that. I also updated that in the doc
