### ISSUE TITLE
Update icons to include Xing

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/Parallax-One#427]
@rodica-andronache what icons are we using in the theme? I see the filename says stamp icons but I can't find this online to see if there's a Xing icon and more icons.

**Comment by rodica-andronache** [comment]
@UVLabs I honestly don't remember exactly , I know they came with the html for parallax one when we bought it.  But maybe it would be a good idea to replace it with font awesome to be more practical, like discussed here https://github.com/Codeinwp/Parallax-One/issues/389

**Comment by UVLabs** [comment]
@rodica-andronache ok yes that would be better

**Comment by petrk94** [comment]
How long will it take until it get integrated?

**Comment by rodica-andronache** [comment]
Hi @petrk94 ,

We are currently working on this, and we'll release an update today.

Regards,
Rodica

**Comment by petrk94** [comment]
Hi @rodica-andronache ,

thanks for the information. Is only a update necessary? Im using Parallax One over a child theme,
does it need to update both?

**Comment by rodica-andronache** [comment]
Hi @petrk94 ,

If you didn't changed files related to the icons selectors in the child theme, you wouldn't have to update anything in there, just the parent theme. After the update, if you have problems, you can let me know and I will try to help you, if there are things that need to be updated in the child theme too.
As an update, we are still working on this. There is a small change that the update will not be ready today, but if this is the case, it will be available in the next day, for sure.

Thank you for understanding,
Rodica

**Comment by rodica-andronache** [comment]
Hi @petrk94 ,

The update is live now. Please let me know if everything is ok.

Regards,
Rodica

**Comment by petrk94** [comment]
Hi @rodica-andronache ,

alright, I will check it today later.

Thanks

**Comment by petrk94** [comment]
Hey @rodica-andronache ,

I have updated the theme and, well I dont know how to explain, it look s**** :/
Why the icon is not in the middle of the site? 
Theres only ONE icon, how can it happen that it look so bad? Please for fix

![middle](https://cloud.githubusercontent.com/assets/19719052/20260792/7bc18a04-aa5b-11e6-8cee-5dfe71023516.PNG)

**Comment by petrk94** [comment]
@rodica-andronache 
I have tried to add another icon but it doesnt changed and I can not remove now the Xing icon.
Honestly, why it make so much problems? Even the link can not be added and not work after saving

![middle](https://cloud.githubusercontent.com/assets/19719052/20261120/d2453550-aa5c-11e6-91ff-07311d8cd4a6.PNG)

**Comment by rodica-andronache** [comment]
Hi @petrk94 ,

I'm so sorry to hear you have this problems with the update. I tested again and for me everything is ok as you can see here http://prnt.sc/d76e4d. As a first stept to see what's the problem, could you please try to clear the cache? Also, there might be something related with the child theme you are using or a conflict with a plugin maybe. Could you please give me your site URL so I can check it?

Thank you,
Rodica

**Comment by petrk94** [comment]
Hi @rodica-andronache ,

How to clear the cache? Im not using any cache plugin. How can I send you a private message?
I dont want show my client website here ;)

**Comment by rodica-andronache** [comment]
Hi @petrk94 ,

Ok, I thought that maybe you use some caching. You can contact us here https://themeisle.com/contact/ . Please mention the link to this issue and that the message is for Rodica, so that it comes directly to me :)

**Comment by petrk94** [comment]
Hi @rodica-andronache ,

thanks, I opened a ticket and wrote you to forward it to you.

**Comment by rodica-andronache** [comment]
Hi @petrk94 ,

I got your message and answered.
