### ISSUE TITLE
No template without page title

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/Parallax-One#428]
There's no template for "full width without title". I think we might also need to do the same thing done in zerif for siteorigin pages @rodica-andronache

**Comment by rodica-andronache** [comment]
Add a template  "Full width, no title (SiteOrigin Page builder Template)"  in template-fullwidth-no-title.php

And add css for site origin compatibility

**Comment by UVLabs** [comment]
@claudiuvertistudio I don't think you added the CSS which only applies for when siteorigin is used on a page to not have the gap in the header

**Comment by claudiuvertistudio** [comment]
it's done. @UVLabs  if you see any problem please tell me

**Comment by UVLabs** [comment]
No problem
