### ISSUE TITLE
Spacing issue in customizer control

### ISSUE THREAD

**Issue by suyogyashukla** [Codeinwp/Parallax-One#438]
There is a minor spacing issue in the customizer control with the latest version of Parallax one in WordPress 4.7 Beta 2. Screenshot [here](https://s15.postimg.org/at7lkjwe3/bugllorix.png).

This happens with all the sections.

**Comment by rodica-andronache** [comment]
@suyogyashukla thanks. We'll reorganize the upsells, which we'll fix this issue https://github.com/Codeinwp/Parallax-One/issues/439 . It will be in the next update
