### ISSUE TITLE
Not able to translate

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/Parallax-One#444]
Few users reported that they weren't able to translate the theme using Polylang. @rodica-andronache

**Comment by rodica-andronache** [comment]
@HardeepAsrani need more details here. None of the strings? or just some?

**Comment by HardeepAsrani** [comment]
@rodica-andronache Most of it, like Services and stuff.

**Comment by rodica-andronache** [comment]
@HardeepAsrani from what I know, it should work. Did you guys tested this or is just the user reporting? Maybe he doesn't know how to use polylang :)

**Comment by HardeepAsrani** [comment]
I tried and didn't work.

**Comment by rodica-andronache** [comment]
@HardeepAsrani the theme should be compatible with wpml and polylang now. If you still see issues let me know
