### ISSUE TITLE
 function 'parallax_one_comment' not found

### ISSUE THREAD

**Issue by vyskoczilova** [Codeinwp/Parallax-One#445]
Since the new update, there is following error and the code is really missing:

```
Warning: call_user_func() expects parameter 1 to be a valid callback, function 'parallax_one_comment' not found or invalid function name in /data/web/virtuals/108982/virtual/www/wp-includes/class-walker-comment.php on line 180
Comments are closed.
```

And Comments are closed even if they are not.

**Comment by rodica-andronache** [comment]
Hi @vyskoczilova ,

Thank you very much for letting us know about this. We just released an update to fix the issue.

Regards,
Rodica

**Comment by vyskoczilova** [comment]
Thanks a lot! Perfect.
