### ISSUE TITLE
Big title text not supporting HTML

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/Parallax-One#452]
@rodica-andronache is this intentional? A user requested to be able to use HTML in the title and subtitle fields.

**Comment by rodica-andronache** [comment]
@UVLabs for me it's working ok http://prnt.sc/eperca . I'm not sure what you mean here

**Comment by UVLabs** [comment]
@rodica-andronache there was a specific html property which was not working but I can't remember it, will reopen if customer replies.
