### ISSUE TITLE
Customizer textarea decodes keyboard brakes to html tags

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/Parallax-One#461]
Breakes appears as <br> tags in Front-end. 

Also html tags are ingored and showed as tags.

http://prntscr.com/f0jogk

**Comment by rodica-andronache** [comment]
fixed here https://github.com/Codeinwp/Parallax-One/commit/b1ee23e2c8dce382c46bc5d96f5c421d0c7c5d00
