### ISSUE TITLE
Broken Blog Page

### ISSUE THREAD

**Issue by brainhappy** [Codeinwp/Parallax-One#462]
I've created a child theme, and seems my blog post page is broken.  It does not feature the feat. img, post title, and no link to actual blog post.  No sidebar is visible either (and I disabled "make all pages full-width in customizer).

Current version running: Version: 2.1.5
No .php files have been modified for the child theme.
Set up front page / blog post page both in Customizer and Settings to relevant pages. (I have tried disabling/enabling settings interchangeably on both customizer and settings to see if it was caused by a bug.  Didn't resolve issue.)

Live website blog page can be found here:  http://www.monicabizier.ca/en/home/

TIA

**Comment by rodica-andronache** [comment]
@cristian-ungureanu can you please investigate this?

**Comment by brainhappy** [comment]
^ Thanks!

**Comment by rodica-andronache** [comment]
Hi @brainhappy ,

I tested on my local environment and everything seems to work ok. I think the problem might be that you are having a multilingual site, and you didn't set up the language for each post. That is why, there is no post display for the English blog here http://www.monicabizier.ca/en/home/ .
If you are using a plugin like Polylang for the translations, you would have to go in the Dashboard to each post, and select the language for it and update the post http://prntscr.com/f1r9fg .

Let me know if you manage to do that.

Regards,
Rodica

**Comment by brainhappy** [comment]
Hi Rodica,

Thanks for your help.  However, this did not resolve the issue, even with a en/fr specific blog pages.  
The blog posts are directly visible (see http://www.monicabizier.ca/en/try1/), but on the blog page (http://www.monicabizier.ca/en/home/), the LINK TO blog posts are unclickable, do not feature the feat. image or post title.

Noemie

**Comment by rodica-andronache** [comment]
Hi @brainhappy ,

In that case, can you please contact us here https://themeisle.com/contact/ so we can get more details? Also, please mention this github issue link in the support message so we can know exactly what's it about.

Thank you,
Rodica
