### ISSUE TITLE
 Call to undefined function get_header();

### ISSUE THREAD

**Issue by Syedwaheed** [Codeinwp/Parallax-One#465]
why am i getting this error on index file while running it on local server "wamp"?

**Comment by rodica-andronache** [comment]
Hi @Syedwaheed ,

I think it might be something related to your WordPress environment. You can read more about this here for example https://www.designwall.com/question/how-to-resolve-get_header-error-in-index-php/ .
It's not something related to the theme.

Regards,
Rodica

**Comment by Syedwaheed** [comment]
Thanks that was my word press problem.
