### ISSUE TITLE
Warnings with WordPress 4.8

### ISSUE THREAD

**Issue by suyogyashukla** [Codeinwp/Parallax-One#467]
Following notices appear when running on WP 4.8 RC1:

Undefined index: product_data in /Applications/MAMP/htdocs/wpnew/wp-content/themes/parallax-one/vendor/themeisle/inc/base.php

Undefined index: product_data in /Applications/MAMP/htdocs/wpnew/wp-content/themes/parallax-one/vendor/themeisle/inc/load.php

same as codeinwp/zerif-pro#700

**Comment by suyogyashukla** [comment]
cc @rodica-andronache @abaicus @cristian-ungureanu

**Comment by suyogyashukla** [comment]
@selul Any idea what's happening here? Is it my WordPress environment? Because @HardeepAsrani gets the warning on his install but @poonam279 and @UVLabs don't

**Comment by selul** [comment]
@suyogyashukla yep, i think so, i has nothing to do with new wordpress as the code si not wordpress dependent

**Comment by suyogyashukla** [comment]
@selul So it's alright to ignore this?

**Comment by selul** [comment]
yep.
