### ISSUE TITLE
Debugging Errors

### ISSUE THREAD

**Issue by suyogyashukla** [Codeinwp/Parallax-One#468]
Following console error appears in Customizer when testing with WordPress 4.8 RC1: 

```Invalid 'X-Frame-Options' header encountered when loading 'http://localhost:8888/test/?customize_changeset_uuid=bd6d6614-e80b-4d8e-9af2-16581d363b06&customize_theme=Parallax-One&customize_messenger_channel=preview-0': 'ALLOW-FROM http://localhost:8888/test/wp-admin/customize.php' is not a recognized directive. The header will be ignored.```

**Comment by suyogyashukla** [comment]
cc @rodica-andronache

**Comment by rodica-andronache** [comment]
@suyogyashukla I tested this too and it's working ok. As we talked before, I think it's something related to your environment so I'll close this :)
