### ISSUE TITLE
ScrollReveal doesn't work

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/Parallax-One#472]
ScrollReveal throws a console error and doesn't work. Same for our demo.

**Comment by RubenMartins** [comment]
Hi, I also ad an error on console wich fixed with this #473 

Please check and give me some feedback if this solves your problem.

If not please send us more information on the console error, if possible a print screen.

**Comment by HardeepAsrani** [comment]
Sure, I'll try in some time and let you know. Thanks for contributing. :)

**Comment by rodica-andronache** [comment]
Hey @RubenMartins ,

Thank you for your contribution. Everything is ok, and we'll release an update today for it.

Regards,
Rodica

**Comment by RubenMartins** [comment]
Perfect @rodica-andronache glad to help
