### ISSUE TITLE
Remove background image from internal pages

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/Parallax-One#63]

**Comment by claudiuvertistudio** [comment]
@rodica-andronache am verificat si pare sa fie ok, atat pe local cat si pe dev2

**Comment by rodica-andronache** [comment]
@claudiuvertistudio mie pe demo tot imi ia imaginea http://prntscr.com/7isutk

**Comment by claudiuvertistudio** [comment]
@rodica-andronache eu am schimbat imaginea de pe background si merge bine, nu stiu de ce la tine nu merge
