### ISSUE TITLE
Check before close divs

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/Parallax-One#70]
parallax_one_logos_section.php

You open two div-s only if some conditions are met, but you close them, in any situation.
http://prntscr.com/7ie54w

**Comment by rodica-andronache** [comment]
same for parallax_one_map_section.php http://prntscr.com/7ie5rv

**Comment by rodica-andronache** [comment]
same for parallax_one_our_story_section.php:
http://prntscr.com/7ie7ju

**Comment by rodica-andronache** [comment]
and probably for others, you should check :)

**Comment by cristian-ungureanu** [comment]
sections are ok

**Comment by rodica-andronache** [comment]
@cristian-ungureanu what do you mean by sections are ok?

**Comment by cristian-ungureanu** [comment]
I checked and the sections are closing ok ... I have an if (smth) echo '<div class='xyz'>' else if (smth2) echo '<div class='xy'>  ... Then i check if smth or smth2 are true and close the div inside this if

**Comment by cristian-ungureanu** [comment]
If smth then echo div class xyz else if smth2 echi div class xy *
