### ISSUE TITLE
Combine customizer controls and simplify naming

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Parallax-One#75]
@rodica-andronache @cristian-ungureanu 

Here are a bit of details on how we should name/ combine customizer to give a bit more space : http://www.awesomescreenshot.com/image/342673/0dd2048aabda69fedec1cd7c324b5537 .

We also need to add : Buy Pro, Forum, Documentation buttons.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu aici mai e de pus : Buy Pro, Forum, Documentation buttons.

**Comment by cristian-ungureanu** [comment]
@ineagu , avem o mica problema, nu putem combina colors cu background image intr-un singur panel. Scenariul este in felul urmator: background image are 4 controale ce trebuie ascunse pe alte pagini decat front page iar culorile trebuie sa fie vizibile mereu. Controalele se ascund folosind active_callback='is_front_page' ... daca pun culorile si controalele de background in aceeasi sectiune si deschid customizerul pe prima pagina, apoi ma duc pe alte pagini cu el deschis, totul functioneaza corect....in schimb daca deschid customizerul pe alta pagina decat front page, doar controlul pentru imagine se ascunde, restul controalelor pentru pozitionarea backgroundului raman vizibile si daca sunt modificate, pagina incepe sa arate urat ... am incercat si eu si rodica sa rezolvam asta, singura solutie a fost sa le lasam separat

**Comment by cristian-ungureanu** [comment]
Am gasit o solutie mai buna...am lasat controalele de colors si background fiecare in secitunea lor si am bagat cele 2 sectiuni in panel
