### ISSUE TITLE
JS error when uploading images

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/Parallax-One#82]
http://prntscr.com/7lke7e

**Comment by cristian-ungureanu** [comment]
se pare ca vom ramane cu eroarea asta...nu stiu ce e si cum sa o rezolv, toate functioneaza ok, doar ca apare eroarea asta... @selu91 , poate te uiti tu peste ea cand ai timp

**Comment by selu91** [comment]
@cristian-ungureanu ok, o sa ma uit azi.

**Comment by cristian-ungureanu** [comment]
@selu91 , ai rezolvat ceva aici?

**Comment by selu91** [comment]
@cristian-ungureanu am rezolvat problema aia, trebuia suprascrisa o functie send_to_editor. asta trimitea poza selectata pe la editor, dar la noi nu il gasea.

**Comment by cristian-ungureanu** [comment]
foarte misto :D , multumesc
