### ISSUE TITLE
Customizer Issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/Parallax-One#97]
@rodica-andronache nu stiu exact pe cine trebuia sa assignez si te-am pus pe tine :) Am descoperit un mic bug in customizer. Cand intri in Header Section -> Logos Bar, dupa ce adaugi un nou field, nu poti adauga link. Cand dai click in chenar sa adaugi link-ul, cursorul se muta instant mai sus. Am pus un video sa vedeti despre ce este vorba.

https://copy.com/Ih07neyl1n4WNYcn

se pare ca aceasta problema exista si la celelalte doua sectiuni: contact si footer section. O rezolvare pe care am gasit-o acum, ar fi sa ti apasat click drepta sa si adaugi link-ul :)

**Comment by cristian-ungureanu** [comment]
@mileamadalin , multumesc de review, ma voi ocupa eu. Totusi nu reusesc sa replic problema, am intrat la logos, am adaugat un box nou, am intrat in el, i-am pus poza, i-am dat click in link dar vad ca merge ok. Aceeasi pasi i-ai facut si tu?

**Comment by mileamadalin** [comment]
@cristian-ungureanu acelasi lucru l-am facut si eu. Mentionez ca eu lucrez mai mult in safari. Acest bug mi-a aparut pe Safari. Daca ai nevoie de ceva, iti pot pune laptopul meu la dispozitie cu team viewer.

**Comment by cristian-ungureanu** [comment]
@mileamadalin , multumesc, am rezolvat
